// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_KPA_H
#define _UI_COMP_KPA_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT kpa
#define UI_COMP_KPA_KPA 0
#define _UI_COMP_KPA_NUM 1
lv_obj_t * ui_kpa_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
