// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT kpa

lv_obj_t * ui_kpa_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_kpa;
    cui_kpa = lv_label_create(comp_parent);
    lv_obj_set_width(cui_kpa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_kpa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_kpa, LV_ALIGN_CENTER);
    lv_label_set_text(cui_kpa, "233kPa");
    lv_obj_set_style_text_color(cui_kpa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_kpa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_KPA_NUM);
    children[UI_COMP_KPA_KPA] = cui_kpa;
    lv_obj_add_event_cb(cui_kpa, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_kpa, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_kpa_create_hook(cui_kpa);
    return cui_kpa;
}

