// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_bg3, &ui_img_1342356983);
    lv_obj_set_width(ui_bg3, LV_SIZE_CONTENT);   /// 815
    lv_obj_set_height(ui_bg3, LV_SIZE_CONTENT);    /// 281
    lv_obj_set_x(ui_bg3, -1);
    lv_obj_set_y(ui_bg3, 198);
    lv_obj_set_align(ui_bg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zzd_off3, &ui_img_896079304);
    lv_obj_set_width(ui_zzd_off3, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_off3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_off3, -361);
    lv_obj_set_y(ui_zzd_off3, -209);
    lv_obj_set_align(ui_zzd_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yzd_off3, &ui_img_1642931740);
    lv_obj_set_width(ui_yzd_off3, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_off3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_off3, 361);
    lv_obj_set_y(ui_yzd_off3, -209);
    lv_obj_set_align(ui_yzd_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zzd_on3, &ui_img_896081354);
    lv_obj_set_width(ui_zzd_on3, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_on3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_on3, -361);
    lv_obj_set_y(ui_zzd_on3, -209);
    lv_obj_set_align(ui_zzd_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_on3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yzd_on3, &ui_img_896082379);
    lv_obj_set_width(ui_yzd_on3, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_on3, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_on3, 361);
    lv_obj_set_y(ui_yzd_on3, -209);
    lv_obj_set_align(ui_yzd_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yhbmp3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yhbmp3, &ui_img_999003654);
    lv_obj_set_width(ui_yhbmp3, LV_SIZE_CONTENT);   /// 649
    lv_obj_set_height(ui_yhbmp3, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_yhbmp3, 2);
    lv_obj_set_y(ui_yhbmp3, -194);
    lv_obj_set_align(ui_yhbmp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yhbmp3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yhbmp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp5 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sxbmp5, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp5, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp5, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp5, -54);
    lv_obj_set_y(ui_sxbmp5, -210);
    lv_obj_set_align(ui_sxbmp5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp6 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sxbmp6, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp6, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp6, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp6, 54);
    lv_obj_set_y(ui_sxbmp6, -210);
    lv_obj_set_align(ui_sxbmp6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time3_hour = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_time3_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3_hour, -32);
    lv_obj_set_y(ui_time3_hour, -220);
    lv_obj_set_align(ui_time3_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time3_hour, "00");
    lv_obj_set_style_text_color(ui_time3_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time3_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time3_hour, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date3, 0);
    lv_obj_set_y(ui_date3, -198);
    lv_obj_set_align(ui_date3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date3, "2024年12月22日");
    lv_obj_set_style_text_color(ui_date3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date3, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tem3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_tem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tem3, 25);
    lv_obj_set_y(ui_tem3, -217);
    lv_obj_set_align(ui_tem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tem3, "00");
    lv_obj_set_style_text_color(ui_tem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tem3, &ui_font_ssd, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssd3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_ssd3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssd3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssd3, 42);
    lv_obj_set_y(ui_ssd3, -216);
    lv_obj_set_align(ui_ssd3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssd3, "℃");
    lv_obj_set_style_text_color(ui_ssd3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssd3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssd3, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mbx3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_mbx3, &ui_img_95555192);
    lv_obj_set_width(ui_mbx3, LV_SIZE_CONTENT);   /// 294
    lv_obj_set_height(ui_mbx3, LV_SIZE_CONTENT);    /// 290
    lv_obj_set_x(ui_mbx3, -264);
    lv_obj_set_y(ui_mbx3, 110);
    lv_obj_set_align(ui_mbx3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbx3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mbx3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mb3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_mb3, &ui_img_1870684104);
    lv_obj_set_width(ui_mb3, LV_SIZE_CONTENT);   /// 254
    lv_obj_set_height(ui_mb3, LV_SIZE_CONTENT);    /// 279
    lv_obj_set_x(ui_mb3, -264);
    lv_obj_set_y(ui_mb3, -29);
    lv_obj_set_align(ui_mb3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mb3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mb3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedbig3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_speedbig3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig3, -274);
    lv_obj_set_y(ui_speedbig3, -78);
    lv_obj_set_align(ui_speedbig3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig3, "240");
    lv_obj_set_style_text_color(ui_speedbig3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig3, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig3, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig3, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedbig4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_speedbig4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig4, -279);
    lv_obj_set_y(ui_speedbig4, -83);
    lv_obj_set_align(ui_speedbig4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig4, "240");
    lv_obj_set_style_text_color(ui_speedbig4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig4, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig4, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig4, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig4, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_mode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode3, -324);
    lv_obj_set_y(ui_mode3, 138);
    lv_obj_set_align(ui_mode3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode3, "P");
    lv_obj_set_style_text_color(ui_mode3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode3, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_mode4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode4, -330);
    lv_obj_set_y(ui_mode4, 134);
    lv_obj_set_align(ui_mode4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode4, "P");
    lv_obj_set_style_text_color(ui_mode4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode4, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode4, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mode4, lv_color_hex(0xFBD96B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mode4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_kmh3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh3, -213);
    lv_obj_set_y(ui_kmh3, 2);
    lv_obj_set_align(ui_kmh3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh3, "km/h");
    lv_obj_set_style_text_color(ui_kmh3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh3, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_kmh4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh4, -216);
    lv_obj_set_y(ui_kmh4, 0);
    lv_obj_set_align(ui_kmh4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh4, "km/h");
    lv_obj_set_style_text_color(ui_kmh4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh4, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh4, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh4, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller3 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Roller3, "经济模式\n运动模式\n环保模式", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller3, 3, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller3, 70);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, -210);
    lv_obj_set_y(ui_Roller3, 163);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller3, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller3, &ui_font_myfond__5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller3, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Roller3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Roller3, &ui_font_myfond__4, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_hgbmp5 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hgbmp5, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp5, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp5, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp5, -210);
    lv_obj_set_y(ui_hgbmp5, 148);
    lv_obj_set_align(ui_hgbmp5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp5, 135);

    ui_hgbmp6 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hgbmp6, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp6, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp6, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp6, -210);
    lv_obj_set_y(ui_hgbmp6, 176);
    lv_obj_set_align(ui_hgbmp6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp6, 135);

    ui_hgbmp7 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hgbmp7, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp7, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp7, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp7, -212);
    lv_obj_set_y(ui_hgbmp7, 131);
    lv_obj_set_align(ui_hgbmp7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp7, 110);

    ui_hgbmp8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hgbmp8, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp8, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp8, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp8, -211);
    lv_obj_set_y(ui_hgbmp8, 194);
    lv_obj_set_align(ui_hgbmp8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp8, 110);

    ui_cmzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_cmzs_off3, &ui_img_525677159);
    lv_obj_set_width(ui_cmzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_off3, -275);
    lv_obj_set_y(ui_cmzs_off3, -224);
    lv_obj_set_align(ui_cmzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ecozs_off3, &ui_img_1717054016);
    lv_obj_set_width(ui_ecozs_off3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_off3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_off3, -75);
    lv_obj_set_y(ui_ecozs_off3, -197);
    lv_obj_set_align(ui_ecozs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ecozs_on3, &ui_img_eco_png);
    lv_obj_set_width(ui_ecozs_on3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_on3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_on3, -75);
    lv_obj_set_y(ui_ecozs_on3, -197);
    lv_obj_set_align(ui_ecozs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_off2_2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_skdzs_off2_2, &ui_img_1837894125);
    lv_obj_set_width(ui_skdzs_off2_2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_off2_2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_off2_2, -110);
    lv_obj_set_y(ui_skdzs_off2_2, -221);
    lv_obj_set_align(ui_skdzs_off2_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_off2_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_off2_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_skdzs_on3, &ui_img_2027284395);
    lv_obj_set_width(ui_skdzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_on3, -110);
    lv_obj_set_y(ui_skdzs_on3, -220);
    lv_obj_set_align(ui_skdzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_dczs_off3, &ui_img_2140545812);
    lv_obj_set_width(ui_dczs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_off3, 101);
    lv_obj_set_y(ui_dczs_off3, -222);
    lv_obj_set_align(ui_dczs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yyzs_off3, &ui_img_2140544787);
    lv_obj_set_width(ui_yyzs_off3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_off3, 138);
    lv_obj_set_y(ui_yyzs_off3, -222);
    lv_obj_set_align(ui_yyzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yjgdzs_off3, &ui_img_2140546837);
    lv_obj_set_width(ui_yjgdzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgdzs_off3, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_yjgdzs_off3, -205);
    lv_obj_set_y(ui_yjgdzs_off3, -221);
    lv_obj_set_align(ui_yjgdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yyzs_on3, &ui_img_946112608);
    lv_obj_set_width(ui_yyzs_on3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_on3, 138);
    lv_obj_set_y(ui_yyzs_on3, -222);
    lv_obj_set_align(ui_yyzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqnzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_aqqnzs_off3, &ui_img_103671251);
    lv_obj_set_width(ui_aqqnzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqnzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqnzs_off3, 266);
    lv_obj_set_y(ui_aqqnzs_off3, -219);
    lv_obj_set_align(ui_aqqnzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqnzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqnzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chgzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_chgzs_off3, &ui_img_624410878);
    lv_obj_set_width(ui_chgzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_chgzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_chgzs_off3, -146);
    lv_obj_set_y(ui_chgzs_off3, -197);
    lv_obj_set_align(ui_chgzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chgzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chgzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qcgzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_qcgzs_off3, &ui_img_457318301);
    lv_obj_set_width(ui_qcgzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qcgzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qcgzs_off3, 139);
    lv_obj_set_y(ui_qcgzs_off3, -198);
    lv_obj_set_align(ui_qcgzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qcgzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qcgzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_aqdzs_off3, &ui_img_1572821649);
    lv_obj_set_width(ui_aqdzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_off3, 101);
    lv_obj_set_y(ui_aqdzs_off3, -199);
    lv_obj_set_align(ui_aqdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zxdzs_off3, &ui_img_1913469232);
    lv_obj_set_width(ui_zxdzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_off3, -74);
    lv_obj_set_y(ui_zxdzs_off3, -221);
    lv_obj_set_align(ui_zxdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_abszs_off3, &ui_img_1185387103);
    lv_obj_set_width(ui_abszs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_off3, 205);
    lv_obj_set_y(ui_abszs_off3, -221);
    lv_obj_set_align(ui_abszs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scpzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_scpzs_off3, &ui_img_2027851014);
    lv_obj_set_width(ui_scpzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_scpzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_scpzs_off3, -111);
    lv_obj_set_y(ui_scpzs_off3, -198);
    lv_obj_set_align(ui_scpzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scpzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scpzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sszs_off3, &ui_img_1092003334);
    lv_obj_set_width(ui_sszs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_off3, 237);
    lv_obj_set_y(ui_sszs_off3, -220);
    lv_obj_set_align(ui_sszs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zszdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zszdzs_off3, &ui_img_1976030069);
    lv_obj_set_width(ui_zszdzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zszdzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zszdzs_off3, 177);
    lv_obj_set_y(ui_zszdzs_off3, -222);
    lv_obj_set_align(ui_zszdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zszdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zszdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qwdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_qwdzs_off3, &ui_img_103657924);
    lv_obj_set_width(ui_qwdzs_off3, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_qwdzs_off3, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_qwdzs_off3, -182);
    lv_obj_set_y(ui_qwdzs_off3, -221);
    lv_obj_set_align(ui_qwdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qwdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qwdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hwdzs_off3, &ui_img_1961040061);
    lv_obj_set_width(ui_hwdzs_off3, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_off3, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_off3, -171);
    lv_obj_set_y(ui_hwdzs_off3, -220);
    lv_obj_set_align(ui_hwdzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_tcszs_off3, &ui_img_1913468209);
    lv_obj_set_width(ui_tcszs_off3, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_off3, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_off3, -145);
    lv_obj_set_y(ui_tcszs_off3, -220);
    lv_obj_set_align(ui_tcszs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_gzzs_off3, &ui_img_457303951);
    lv_obj_set_width(ui_gzzs_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_off3, 72);
    lv_obj_set_y(ui_gzzs_off3, -221);
    lv_obj_set_align(ui_gzzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_wxbjsgd_off3, &ui_img_525662809);
    lv_obj_set_width(ui_wxbjsgd_off3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_off3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_off3, 72);
    lv_obj_set_y(ui_wxbjsgd_off3, -198);
    lv_obj_set_align(ui_wxbjsgd_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_off3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_fdjzs_off3, &ui_img_1926959430);
    lv_obj_set_width(ui_fdjzs_off3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_off3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_off3, -243);
    lv_obj_set_y(ui_fdjzs_off3, -221);
    lv_obj_set_align(ui_fdjzs_off3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_off3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_off3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_fdjzs_on3, &ui_img_986460666);
    lv_obj_set_width(ui_fdjzs_on3, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_on3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_on3, -243);
    lv_obj_set_y(ui_fdjzs_on3, -221);
    lv_obj_set_align(ui_fdjzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_yon3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_abszs_yon3, &ui_img_1539047480);
    lv_obj_set_width(ui_abszs_yon3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_yon3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_yon3, 205);
    lv_obj_set_y(ui_abszs_yon3, -220);
    lv_obj_set_align(ui_abszs_yon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_yon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_yon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_yon3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sszs_yon3, &ui_img_2027837687);
    lv_obj_set_width(ui_sszs_yon3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_yon3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_yon3, 237);
    lv_obj_set_y(ui_sszs_yon3, -220);
    lv_obj_set_align(ui_sszs_yon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_yon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_yon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hwdzs_on3, &ui_img_1913482559);
    lv_obj_set_width(ui_hwdzs_on3, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_on3, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_on3, -171);
    lv_obj_set_y(ui_hwdzs_on3, -220);
    lv_obj_set_align(ui_hwdzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqmzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_aqqmzs_on3, &ui_img_457319324);
    lv_obj_set_width(ui_aqqmzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqmzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqmzs_on3, 266);
    lv_obj_set_y(ui_aqqmzs_on3, -219);
    lv_obj_set_align(ui_aqqmzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqmzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqmzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hcgzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hcgzs_on3, &ui_img_103672274);
    lv_obj_set_width(ui_hcgzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_hcgzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_hcgzs_on3, -146);
    lv_obj_set_y(ui_hcgzs_on3, -197);
    lv_obj_set_align(ui_hcgzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hcgzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hcgzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qsgzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_qsgzs_on3, &ui_img_1539048503);
    lv_obj_set_width(ui_qsgzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qsgzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qsgzs_on3, 139);
    lv_obj_set_y(ui_qsgzs_on3, -198);
    lv_obj_set_align(ui_qsgzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qsgzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qsgzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_cmzs_on3, &ui_img_1961051338);
    lv_obj_set_width(ui_cmzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_on3, -275);
    lv_obj_set_y(ui_cmzs_on3, -224);
    lv_obj_set_align(ui_cmzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_aqdzs_on3, &ui_img_457316251);
    lv_obj_set_width(ui_aqdzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_on3, 102);
    lv_obj_set_y(ui_aqdzs_on3, -199);
    lv_obj_set_align(ui_aqdzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_dczs_on3, &ui_img_1539045430);
    lv_obj_set_width(ui_dczs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_on3, 101);
    lv_obj_set_y(ui_dczs_on3, -222);
    lv_obj_set_align(ui_dczs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_tcszs_on3, &ui_img_946110558);
    lv_obj_set_width(ui_tcszs_on3, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_on3, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_on3, -145);
    lv_obj_set_y(ui_tcszs_on3, -220);
    lv_obj_set_align(ui_tcszs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zxdzs_on3, &ui_img_1539046453);
    lv_obj_set_width(ui_zxdzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_on3, -74);
    lv_obj_set_y(ui_zxdzs_on3, -220);
    lv_obj_set_align(ui_zxdzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_wxbjsgd_on3, &ui_img_2027838714);
    lv_obj_set_width(ui_wxbjsgd_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_on3, 72);
    lv_obj_set_y(ui_wxbjsgd_on3, -198);
    lv_obj_set_align(ui_wxbjsgd_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_gzzs_on3, &ui_img_1185399403);
    lv_obj_set_width(ui_gzzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_on3, 72);
    lv_obj_set_y(ui_gzzs_on3, -221);
    lv_obj_set_align(ui_gzzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_ron3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_abszs_ron3, &ui_img_1913481532);
    lv_obj_set_width(ui_abszs_ron3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_ron3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_ron3, 206);
    lv_obj_set_y(ui_abszs_ron3, -221);
    lv_obj_set_align(ui_abszs_ron3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_ron3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_ron3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cspzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_cspzs_on3, &ui_img_946109535);
    lv_obj_set_width(ui_cspzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cspzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cspzs_on3, -111);
    lv_obj_set_y(ui_cspzs_on3, -198);
    lv_obj_set_align(ui_cspzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cspzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cspzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_ron3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sszs_ron3, &ui_img_525673059);
    lv_obj_set_width(ui_sszs_ron3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_ron3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_ron3, 237);
    lv_obj_set_y(ui_sszs_ron3, -220);
    lv_obj_set_align(ui_sszs_ron3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_ron3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_ron3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zczdzs_on3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zczdzs_on3, &ui_img_457314201);
    lv_obj_set_width(ui_zczdzs_on3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zczdzs_on3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zczdzs_on3, 177);
    lv_obj_set_y(ui_zczdzs_on3, -222);
    lv_obj_set_align(ui_zczdzs_on3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zczdzs_on3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zczdzs_on3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_jon3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yjgd_jon3, &ui_img_103667151);
    lv_obj_set_width(ui_yjgd_jon3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_jon3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_jon3, -205);
    lv_obj_set_y(ui_yjgd_jon3, -220);
    lv_obj_set_align(ui_yjgd_jon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_jon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_jon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_yon3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_yjgd_yon3, &ui_img_170937940);
    lv_obj_set_width(ui_yjgd_yon3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_yon3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_yon3, -206);
    lv_obj_set_y(ui_yjgd_yon3, -221);
    lv_obj_set_align(ui_yjgd_yon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_yon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_yon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leijilicbmp = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_leijilicbmp, &ui_img_95451801);
    lv_obj_set_width(ui_leijilicbmp, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_leijilicbmp, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_leijilicbmp, -73);
    lv_obj_set_y(ui_leijilicbmp, -72);
    lv_obj_set_align(ui_leijilicbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leijilicbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leijilicbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leijisjbmp = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_leijisjbmp, &ui_img_999005704);
    lv_obj_set_width(ui_leijisjbmp, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_leijisjbmp, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_leijisjbmp, 50);
    lv_obj_set_y(ui_leijisjbmp, -72);
    lv_obj_set_align(ui_leijisjbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leijisjbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leijisjbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zonlicbmp = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zonlicbmp, &ui_img_667405251);
    lv_obj_set_width(ui_zonlicbmp, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_zonlicbmp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zonlicbmp, 320);
    lv_obj_set_y(ui_zonlicbmp, -72);
    lv_obj_set_align(ui_zonlicbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zonlicbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zonlicbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leijihaoyoubmp = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_leijihaoyoubmp, &ui_img_457315224);
    lv_obj_set_width(ui_leijihaoyoubmp, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_leijihaoyoubmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_leijihaoyoubmp, 181);
    lv_obj_set_y(ui_leijihaoyoubmp, -72);
    lv_obj_set_align(ui_leijihaoyoubmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leijihaoyoubmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leijihaoyoubmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KMbmp1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_KMbmp1, &ui_img_km_png);
    lv_obj_set_width(ui_KMbmp1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_KMbmp1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_KMbmp1, -74);
    lv_obj_set_y(ui_KMbmp1, 129);
    lv_obj_set_align(ui_KMbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KMbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KMbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KMbmp2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_KMbmp2, &ui_img_km_png);
    lv_obj_set_width(ui_KMbmp2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_KMbmp2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_KMbmp2, 320);
    lv_obj_set_y(ui_KMbmp2, 129);
    lv_obj_set_align(ui_KMbmp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KMbmp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KMbmp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hbmp1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Hbmp1, &ui_img_h_png);
    lv_obj_set_width(ui_Hbmp1, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Hbmp1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Hbmp1, 50);
    lv_obj_set_y(ui_Hbmp1, 129);
    lv_obj_set_align(ui_Hbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LKMbmp1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_LKMbmp1, &ui_img_100km_png);
    lv_obj_set_width(ui_LKMbmp1, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_LKMbmp1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_LKMbmp1, 180);
    lv_obj_set_y(ui_LKMbmp1, 129);
    lv_obj_set_align(ui_LKMbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LKMbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LKMbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_titlebgbmp = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_titlebgbmp, &ui_img_1482924002);
    lv_obj_set_width(ui_titlebgbmp, LV_SIZE_CONTENT);   /// 355
    lv_obj_set_height(ui_titlebgbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_titlebgbmp, 125);
    lv_obj_set_y(ui_titlebgbmp, -128);
    lv_obj_set_align(ui_titlebgbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_titlebgbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_titlebgbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_title = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, 124);
    lv_obj_set_y(ui_title, -128);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "累计里程  长按OK键清除记录");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title, &ui_font_myfond__2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leijilicconer = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_leijilicconer);
    lv_obj_set_width(ui_leijilicconer, 100);
    lv_obj_set_height(ui_leijilicconer, 50);
    lv_obj_set_x(ui_leijilicconer, -73);
    lv_obj_set_y(ui_leijilicconer, 27);
    lv_obj_set_align(ui_leijilicconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leijilicconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_leijilicconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leijilicconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leijilic_value = lv_label_create(ui_leijilicconer);
    lv_obj_set_width(ui_leijilic_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leijilic_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leijilic_value, -76);
    lv_obj_set_y(ui_leijilic_value, 27);
    lv_obj_set_align(ui_leijilic_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leijilic_value, "9999");
    lv_obj_set_style_text_color(ui_leijilic_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leijilic_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leijilic_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leijisjconer = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_leijisjconer);
    lv_obj_set_width(ui_leijisjconer, 127);
    lv_obj_set_height(ui_leijisjconer, 50);
    lv_obj_set_x(ui_leijisjconer, 50);
    lv_obj_set_y(ui_leijisjconer, 27);
    lv_obj_set_align(ui_leijisjconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leijisjconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_leijisjconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leijisjconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_leijisjconer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leijisjh_value = lv_label_create(ui_leijisjconer);
    lv_obj_set_width(ui_leijisjh_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leijisjh_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leijisjh_value, 67);
    lv_obj_set_y(ui_leijisjh_value, 58);
    lv_obj_set_align(ui_leijisjh_value, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leijisjh_value, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_leijisjh_value, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_leijisjh_value, "0");
    lv_obj_set_style_text_color(ui_leijisjh_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leijisjh_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_leijisjh_value, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leijisjh_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sjmh = lv_label_create(ui_leijisjconer);
    lv_obj_set_width(ui_sjmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sjmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sjmh, 69);
    lv_obj_set_y(ui_sjmh, 26);
    lv_obj_set_align(ui_sjmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sjmh, ":");
    lv_obj_set_style_text_color(ui_sjmh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sjmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sjmh, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leijisjm_value = lv_label_create(ui_leijisjconer);
    lv_obj_set_width(ui_leijisjm_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leijisjm_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_leijisjm_value, 95);
    lv_obj_set_y(ui_leijisjm_value, 27);
    lv_obj_set_align(ui_leijisjm_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leijisjm_value, "0");
    lv_obj_set_scroll_dir(ui_leijisjm_value, LV_DIR_LEFT);
    lv_obj_set_style_text_color(ui_leijisjm_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leijisjm_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leijisjm_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liejiyouhaoconner = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_liejiyouhaoconner);
    lv_obj_set_width(ui_liejiyouhaoconner, 122);
    lv_obj_set_height(ui_liejiyouhaoconner, 50);
    lv_obj_set_x(ui_liejiyouhaoconner, 181);
    lv_obj_set_y(ui_liejiyouhaoconner, 27);
    lv_obj_set_align(ui_liejiyouhaoconner, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_liejiyouhaoconner, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_liejiyouhaoconner, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_liejiyouhaoconner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_haoyouL_value = lv_label_create(ui_liejiyouhaoconner);
    lv_obj_set_width(ui_haoyouL_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_haoyouL_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_haoyouL_value, 158);
    lv_obj_set_y(ui_haoyouL_value, 27);
    lv_obj_set_align(ui_haoyouL_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_haoyouL_value, "0");
    lv_obj_set_scroll_dir(ui_haoyouL_value, LV_DIR_RIGHT);
    lv_obj_set_style_text_color(ui_haoyouL_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_haoyouL_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_haoyouL_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_haoyoud = lv_label_create(ui_liejiyouhaoconner);
    lv_obj_set_width(ui_haoyoud, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_haoyoud, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_haoyoud, 185);
    lv_obj_set_y(ui_haoyoud, 27);
    lv_obj_set_align(ui_haoyoud, LV_ALIGN_CENTER);
    lv_label_set_text(ui_haoyoud, ".");
    lv_obj_set_style_text_color(ui_haoyoud, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_haoyoud, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_haoyoud, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_haoyoudL_value = lv_label_create(ui_liejiyouhaoconner);
    lv_obj_set_width(ui_haoyoudL_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_haoyoudL_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_haoyoudL_value, 209);
    lv_obj_set_y(ui_haoyoudL_value, 27);
    lv_obj_set_align(ui_haoyoudL_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_haoyoudL_value, "0");
    lv_obj_set_scroll_dir(ui_haoyoudL_value, LV_DIR_LEFT);
    lv_obj_set_style_text_color(ui_haoyoudL_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_haoyoudL_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_haoyoudL_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zonlicconer = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_zonlicconer);
    lv_obj_set_width(ui_zonlicconer, 139);
    lv_obj_set_height(ui_zonlicconer, 50);
    lv_obj_set_x(ui_zonlicconer, 320);
    lv_obj_set_y(ui_zonlicconer, 26);
    lv_obj_set_align(ui_zonlicconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_zonlicconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_zonlicconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_zonlicconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zonlic_value = lv_label_create(ui_zonlicconer);
    lv_obj_set_width(ui_zonlic_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zonlic_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zonlic_value, 309);
    lv_obj_set_y(ui_zonlic_value, 27);
    lv_obj_set_align(ui_zonlic_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zonlic_value, "99999");
    lv_obj_set_style_text_color(ui_zonlic_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zonlic_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zonlic_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time3_mh = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_time3_mh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3_mh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3_mh, -17);
    lv_obj_set_y(ui_time3_mh, -220);
    lv_obj_set_align(ui_time3_mh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time3_mh, ":");
    lv_obj_set_style_text_color(ui_time3_mh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time3_mh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time3_mh, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time3_min = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_time3_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3_min, -1);
    lv_obj_set_y(ui_time3_min, -220);
    lv_obj_set_align(ui_time3_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time3_min, "00");
    lv_obj_set_style_text_color(ui_time3_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time3_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time3_min, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
