// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_bg2, &ui_img_1342356983);
    lv_obj_set_width(ui_bg2, LV_SIZE_CONTENT);   /// 815
    lv_obj_set_height(ui_bg2, LV_SIZE_CONTENT);    /// 281
    lv_obj_set_x(ui_bg2, -1);
    lv_obj_set_y(ui_bg2, 198);
    lv_obj_set_align(ui_bg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zzd_off2, &ui_img_896079304);
    lv_obj_set_width(ui_zzd_off2, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_off2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_off2, -361);
    lv_obj_set_y(ui_zzd_off2, -209);
    lv_obj_set_align(ui_zzd_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yzd_off2, &ui_img_1642931740);
    lv_obj_set_width(ui_yzd_off2, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_off2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_off2, 361);
    lv_obj_set_y(ui_yzd_off2, -209);
    lv_obj_set_align(ui_yzd_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zzd_on2, &ui_img_896081354);
    lv_obj_set_width(ui_zzd_on2, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_on2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_on2, -361);
    lv_obj_set_y(ui_zzd_on2, -209);
    lv_obj_set_align(ui_zzd_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yzd_on2, &ui_img_896082379);
    lv_obj_set_width(ui_yzd_on2, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_on2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_on2, 361);
    lv_obj_set_y(ui_yzd_on2, -209);
    lv_obj_set_align(ui_yzd_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yhbmp2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yhbmp2, &ui_img_999003654);
    lv_obj_set_width(ui_yhbmp2, LV_SIZE_CONTENT);   /// 649
    lv_obj_set_height(ui_yhbmp2, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_yhbmp2, 2);
    lv_obj_set_y(ui_yhbmp2, -194);
    lv_obj_set_align(ui_yhbmp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yhbmp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yhbmp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sxbmp3, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp3, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp3, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp3, -54);
    lv_obj_set_y(ui_sxbmp3, -210);
    lv_obj_set_align(ui_sxbmp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sxbmp4, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp4, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp4, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp4, 54);
    lv_obj_set_y(ui_sxbmp4, -210);
    lv_obj_set_align(ui_sxbmp4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time2_hour = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_time2_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2_hour, -32);
    lv_obj_set_y(ui_time2_hour, -220);
    lv_obj_set_align(ui_time2_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2_hour, "00");
    lv_obj_set_style_text_color(ui_time2_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2_hour, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date2, 0);
    lv_obj_set_y(ui_date2, -198);
    lv_obj_set_align(ui_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date2, "2024年12月22日");
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tem2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tem2, 25);
    lv_obj_set_y(ui_tem2, -217);
    lv_obj_set_align(ui_tem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tem2, "00");
    lv_obj_set_style_text_color(ui_tem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tem2, &ui_font_ssd, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssd2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ssd2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssd2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssd2, 42);
    lv_obj_set_y(ui_ssd2, -216);
    lv_obj_set_align(ui_ssd2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssd2, "℃");
    lv_obj_set_style_text_color(ui_ssd2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssd2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssd2, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mbx2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_mbx2, &ui_img_95555192);
    lv_obj_set_width(ui_mbx2, LV_SIZE_CONTENT);   /// 294
    lv_obj_set_height(ui_mbx2, LV_SIZE_CONTENT);    /// 290
    lv_obj_set_x(ui_mbx2, -264);
    lv_obj_set_y(ui_mbx2, 110);
    lv_obj_set_align(ui_mbx2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbx2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mbx2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mbs2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_mbs2, &ui_img_1870684104);
    lv_obj_set_width(ui_mbs2, LV_SIZE_CONTENT);   /// 296
    lv_obj_set_height(ui_mbs2, LV_SIZE_CONTENT);    /// 321
    lv_obj_set_x(ui_mbs2, -264);
    lv_obj_set_y(ui_mbs2, -29);
    lv_obj_set_align(ui_mbs2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbs2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mbs2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedbig21 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_speedbig21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig21, -274);
    lv_obj_set_y(ui_speedbig21, -78);
    lv_obj_set_align(ui_speedbig21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig21, "240");
    lv_obj_set_style_text_color(ui_speedbig21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig21, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig21, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig21, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedbig22 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_speedbig22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig22, -279);
    lv_obj_set_y(ui_speedbig22, -83);
    lv_obj_set_align(ui_speedbig22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig22, "240");
    lv_obj_set_style_text_color(ui_speedbig22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig22, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig22, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig22, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig22, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode21 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_mode21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode21, -324);
    lv_obj_set_y(ui_mode21, 138);
    lv_obj_set_align(ui_mode21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode21, "P");
    lv_obj_set_style_text_color(ui_mode21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode21, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode22 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_mode22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode22, -330);
    lv_obj_set_y(ui_mode22, 134);
    lv_obj_set_align(ui_mode22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode22, "P");
    lv_obj_set_style_text_color(ui_mode22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode22, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode22, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mode22, lv_color_hex(0xFBD96B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mode22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh21 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kmh21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh21, -213);
    lv_obj_set_y(ui_kmh21, 2);
    lv_obj_set_align(ui_kmh21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh21, "km/h");
    lv_obj_set_style_text_color(ui_kmh21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh21, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh21, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh22 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kmh22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh22, -216);
    lv_obj_set_y(ui_kmh22, 0);
    lv_obj_set_align(ui_kmh22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh22, "km/h");
    lv_obj_set_style_text_color(ui_kmh22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh22, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh22, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh22, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_greedbox1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_greedbox1, &ui_img_rl_card_png);
    lv_obj_set_width(ui_greedbox1, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_greedbox1, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_greedbox1, 7);
    lv_obj_set_y(ui_greedbox1, -68);
    lv_obj_set_align(ui_greedbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greedbox1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greedbox1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_greedbox2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_greedbox2, &ui_img_rl_card_png);
    lv_obj_set_width(ui_greedbox2, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_greedbox2, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_greedbox2, 199);
    lv_obj_set_y(ui_greedbox2, -68);
    lv_obj_set_align(ui_greedbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greedbox2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greedbox2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_greedbox3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_greedbox3, &ui_img_rl_card_png);
    lv_obj_set_width(ui_greedbox3, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_greedbox3, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_greedbox3, 7);
    lv_obj_set_y(ui_greedbox3, 111);
    lv_obj_set_align(ui_greedbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greedbox3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greedbox3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_greedbox4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_greedbox4, &ui_img_rl_card_png);
    lv_obj_set_width(ui_greedbox4, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_greedbox4, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_greedbox4, 199);
    lv_obj_set_y(ui_greedbox4, 110);
    lv_obj_set_align(ui_greedbox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greedbox4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greedbox4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redbox1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_redbox1, &ui_img_fr_card_png);
    lv_obj_set_width(ui_redbox1, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_redbox1, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_redbox1, 7);
    lv_obj_set_y(ui_redbox1, -68);
    lv_obj_set_align(ui_redbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redbox1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redbox1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redbox2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_redbox2, &ui_img_fr_card_png);
    lv_obj_set_width(ui_redbox2, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_redbox2, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_redbox2, 199);
    lv_obj_set_y(ui_redbox2, -68);
    lv_obj_set_align(ui_redbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redbox2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redbox2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redbox3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_redbox3, &ui_img_fr_card_png);
    lv_obj_set_width(ui_redbox3, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_redbox3, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_redbox3, 7);
    lv_obj_set_y(ui_redbox3, 110);
    lv_obj_set_align(ui_redbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redbox3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redbox3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redbox4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_redbox4, &ui_img_fr_card_png);
    lv_obj_set_width(ui_redbox4, LV_SIZE_CONTENT);   /// 183
    lv_obj_set_height(ui_redbox4, LV_SIZE_CONTENT);    /// 173
    lv_obj_set_x(ui_redbox4, 199);
    lv_obj_set_y(ui_redbox4, 110);
    lv_obj_set_align(ui_redbox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redbox4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redbox4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_catlun = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_catlun, &ui_img_tyres_png);
    lv_obj_set_width(ui_catlun, LV_SIZE_CONTENT);   /// 105
    lv_obj_set_height(ui_catlun, LV_SIZE_CONTENT);    /// 196
    lv_obj_set_x(ui_catlun, 103);
    lv_obj_set_y(ui_catlun, 22);
    lv_obj_set_align(ui_catlun, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_catlun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_catlun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cat = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_cat, &ui_img_car_png);
    lv_obj_set_width(ui_cat, LV_SIZE_CONTENT);   /// 135
    lv_obj_set_height(ui_cat, LV_SIZE_CONTENT);    /// 285
    lv_obj_set_x(ui_cat, 103);
    lv_obj_set_y(ui_cat, 23);
    lv_obj_set_align(ui_cat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_kpa1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kpa1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kpa1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kpa1, -36);
    lv_obj_set_y(ui_kpa1, -129);
    lv_obj_set_align(ui_kpa1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kpa1, "233kPa");
    lv_obj_set_style_text_color(ui_kpa1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kpa1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kpa1, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kpa2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kpa2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kpa2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kpa2, 242);
    lv_obj_set_y(ui_kpa2, -129);
    lv_obj_set_align(ui_kpa2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kpa2, "233kPa");
    lv_obj_set_style_text_color(ui_kpa2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kpa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kpa2, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kpa3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kpa3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kpa3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kpa3, -36);
    lv_obj_set_y(ui_kpa3, 174);
    lv_obj_set_align(ui_kpa3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kpa3, "233kPa");
    lv_obj_set_style_text_color(ui_kpa3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kpa3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kpa3, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kpa4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_kpa4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kpa4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kpa4, 242);
    lv_obj_set_y(ui_kpa4, 171);
    lv_obj_set_align(ui_kpa4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kpa4, "233kPa");
    lv_obj_set_style_text_color(ui_kpa4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kpa4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kpa4, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lttem1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lttem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lttem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lttem1, -50);
    lv_obj_set_y(ui_lttem1, -102);
    lv_obj_set_align(ui_lttem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lttem1, "34°C");
    lv_obj_set_style_text_color(ui_lttem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lttem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lttem1, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lttem2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lttem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lttem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lttem2, 256);
    lv_obj_set_y(ui_lttem2, -100);
    lv_obj_set_align(ui_lttem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lttem2, "34°C");
    lv_obj_set_style_text_color(ui_lttem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lttem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lttem2, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lttem3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lttem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lttem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lttem3, -50);
    lv_obj_set_y(ui_lttem3, 147);
    lv_obj_set_align(ui_lttem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lttem3, "34°C");
    lv_obj_set_style_text_color(ui_lttem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lttem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lttem3, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lttem4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lttem4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lttem4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lttem4, 256);
    lv_obj_set_y(ui_lttem4, 146);
    lv_obj_set_align(ui_lttem4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lttem4, "34°C");
    lv_obj_set_style_text_color(ui_lttem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lttem4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lttem4, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tyjgz1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tyjgz1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tyjgz1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tyjgz1, -47);
    lv_obj_set_y(ui_tyjgz1, -2);
    lv_obj_set_align(ui_tyjgz1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tyjgz1, "胎压过低");
    lv_obj_set_style_text_color(ui_tyjgz1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tyjgz1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tyjgz1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tyjgz1, &ui_font_myfond__4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tyjgz2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tyjgz2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tyjgz2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tyjgz2, -47);
    lv_obj_set_y(ui_tyjgz2, 44);
    lv_obj_set_align(ui_tyjgz2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tyjgz2, "胎压过低");
    lv_obj_set_style_text_color(ui_tyjgz2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tyjgz2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tyjgz2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tyjgz2, &ui_font_myfond__4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tyjgy1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tyjgy1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tyjgy1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tyjgy1, 252);
    lv_obj_set_y(ui_tyjgy1, -2);
    lv_obj_set_align(ui_tyjgy1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tyjgy1, "胎压过低");
    lv_obj_set_style_text_color(ui_tyjgy1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tyjgy1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tyjgy1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tyjgy1, &ui_font_myfond__4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tyjgy2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tyjgy2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tyjgy2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tyjgy2, 253);
    lv_obj_set_y(ui_tyjgy2, 42);
    lv_obj_set_align(ui_tyjgy2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tyjgy2, "胎压过低");
    lv_obj_set_style_text_color(ui_tyjgy2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tyjgy2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tyjgy2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tyjgy2, &ui_font_myfond__4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aqd1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqd1, &ui_img_457316251);
    lv_obj_set_width(ui_aqd1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqd1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqd1, 83);
    lv_obj_set_y(ui_aqd1, -7);
    lv_obj_set_align(ui_aqd1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqd1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqd1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqd2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqd2, &ui_img_457316251);
    lv_obj_set_width(ui_aqd2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqd2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqd2, 121);
    lv_obj_set_y(ui_aqd2, -7);
    lv_obj_set_align(ui_aqd2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqd2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqd2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqd3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqd3, &ui_img_457316251);
    lv_obj_set_width(ui_aqd3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqd3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqd3, 80);
    lv_obj_set_y(ui_aqd3, 65);
    lv_obj_set_align(ui_aqd3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqd3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqd3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqd4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqd4, &ui_img_457316251);
    lv_obj_set_width(ui_aqd4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqd4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqd4, 102);
    lv_obj_set_y(ui_aqd4, 65);
    lv_obj_set_align(ui_aqd4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqd4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqd4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqd5 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqd5, &ui_img_457316251);
    lv_obj_set_width(ui_aqd5, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqd5, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqd5, 125);
    lv_obj_set_y(ui_aqd5, 65);
    lv_obj_set_align(ui_aqd5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqd5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqd5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_Screen2);
    lv_roller_set_options(ui_Roller1, "经济模式\n运动模式\n环保模式", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller1, 2, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller1, 70);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, -210);
    lv_obj_set_y(ui_Roller1, 163);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_myfond__5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Roller1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Roller1, &ui_font_myfond__4, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_hgbmp22 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hgbmp22, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp22, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp22, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp22, -210);
    lv_obj_set_y(ui_hgbmp22, 148);
    lv_obj_set_align(ui_hgbmp22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp22, 135);

    ui_hgbmp23 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hgbmp23, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp23, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp23, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp23, -210);
    lv_obj_set_y(ui_hgbmp23, 176);
    lv_obj_set_align(ui_hgbmp23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp23, 135);

    ui_hgbmp21 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hgbmp21, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp21, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp21, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp21, -212);
    lv_obj_set_y(ui_hgbmp21, 131);
    lv_obj_set_align(ui_hgbmp21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp21, 110);

    ui_hgbmp24 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hgbmp24, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp24, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp24, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp24, -211);
    lv_obj_set_y(ui_hgbmp24, 194);
    lv_obj_set_align(ui_hgbmp24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp24, 110);

    ui_cmzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_cmzs_off2, &ui_img_525677159);
    lv_obj_set_width(ui_cmzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_off2, -275);
    lv_obj_set_y(ui_cmzs_off2, -224);
    lv_obj_set_align(ui_cmzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_ecozs_off2, &ui_img_1717054016);
    lv_obj_set_width(ui_ecozs_off2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_off2, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_off2, -75);
    lv_obj_set_y(ui_ecozs_off2, -197);
    lv_obj_set_align(ui_ecozs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_ecozs_on2, &ui_img_eco_png);
    lv_obj_set_width(ui_ecozs_on2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_on2, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_on2, -75);
    lv_obj_set_y(ui_ecozs_on2, -197);
    lv_obj_set_align(ui_ecozs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_off2_ = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_skdzs_off2_, &ui_img_1837894125);
    lv_obj_set_width(ui_skdzs_off2_, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_off2_, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_off2_, -110);
    lv_obj_set_y(ui_skdzs_off2_, -221);
    lv_obj_set_align(ui_skdzs_off2_, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_off2_, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_off2_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_skdzs_on2, &ui_img_2027284395);
    lv_obj_set_width(ui_skdzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_on2, -110);
    lv_obj_set_y(ui_skdzs_on2, -220);
    lv_obj_set_align(ui_skdzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_dczs_off2, &ui_img_2140545812);
    lv_obj_set_width(ui_dczs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_off2, 101);
    lv_obj_set_y(ui_dczs_off2, -222);
    lv_obj_set_align(ui_dczs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yyzs_off2, &ui_img_2140544787);
    lv_obj_set_width(ui_yyzs_off2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_off2, 138);
    lv_obj_set_y(ui_yyzs_off2, -222);
    lv_obj_set_align(ui_yyzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yjgdzs_off2, &ui_img_2140546837);
    lv_obj_set_width(ui_yjgdzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgdzs_off2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_yjgdzs_off2, -205);
    lv_obj_set_y(ui_yjgdzs_off2, -221);
    lv_obj_set_align(ui_yjgdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yyzs_on2, &ui_img_946112608);
    lv_obj_set_width(ui_yyzs_on2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_on2, 138);
    lv_obj_set_y(ui_yyzs_on2, -222);
    lv_obj_set_align(ui_yyzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqnzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqqnzs_off2, &ui_img_103671251);
    lv_obj_set_width(ui_aqqnzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqnzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqnzs_off2, 266);
    lv_obj_set_y(ui_aqqnzs_off2, -219);
    lv_obj_set_align(ui_aqqnzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqnzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqnzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chgzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_chgzs_off2, &ui_img_624410878);
    lv_obj_set_width(ui_chgzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_chgzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_chgzs_off2, -146);
    lv_obj_set_y(ui_chgzs_off2, -197);
    lv_obj_set_align(ui_chgzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chgzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chgzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qcgzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_qcgzs_off2, &ui_img_457318301);
    lv_obj_set_width(ui_qcgzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qcgzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qcgzs_off2, 139);
    lv_obj_set_y(ui_qcgzs_off2, -198);
    lv_obj_set_align(ui_qcgzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qcgzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qcgzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqdzs_off2, &ui_img_1572821649);
    lv_obj_set_width(ui_aqdzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_off2, 101);
    lv_obj_set_y(ui_aqdzs_off2, -199);
    lv_obj_set_align(ui_aqdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zxdzs_off2, &ui_img_1913469232);
    lv_obj_set_width(ui_zxdzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_off2, -74);
    lv_obj_set_y(ui_zxdzs_off2, -221);
    lv_obj_set_align(ui_zxdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_abszs_off2, &ui_img_1185387103);
    lv_obj_set_width(ui_abszs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_off2, 205);
    lv_obj_set_y(ui_abszs_off2, -221);
    lv_obj_set_align(ui_abszs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scpzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_scpzs_off2, &ui_img_2027851014);
    lv_obj_set_width(ui_scpzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_scpzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_scpzs_off2, -111);
    lv_obj_set_y(ui_scpzs_off2, -198);
    lv_obj_set_align(ui_scpzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scpzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scpzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sszs_off2, &ui_img_1092003334);
    lv_obj_set_width(ui_sszs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_off2, 237);
    lv_obj_set_y(ui_sszs_off2, -220);
    lv_obj_set_align(ui_sszs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zszdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zszdzs_off2, &ui_img_1976030069);
    lv_obj_set_width(ui_zszdzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zszdzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zszdzs_off2, 177);
    lv_obj_set_y(ui_zszdzs_off2, -222);
    lv_obj_set_align(ui_zszdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zszdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zszdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qwdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_qwdzs_off2, &ui_img_103657924);
    lv_obj_set_width(ui_qwdzs_off2, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_qwdzs_off2, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_qwdzs_off2, -182);
    lv_obj_set_y(ui_qwdzs_off2, -221);
    lv_obj_set_align(ui_qwdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qwdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qwdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hwdzs_off2, &ui_img_1961040061);
    lv_obj_set_width(ui_hwdzs_off2, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_off2, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_off2, -171);
    lv_obj_set_y(ui_hwdzs_off2, -220);
    lv_obj_set_align(ui_hwdzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_tcszs_off2, &ui_img_1913468209);
    lv_obj_set_width(ui_tcszs_off2, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_off2, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_off2, -145);
    lv_obj_set_y(ui_tcszs_off2, -220);
    lv_obj_set_align(ui_tcszs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_gzzs_off2, &ui_img_457303951);
    lv_obj_set_width(ui_gzzs_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_off2, 72);
    lv_obj_set_y(ui_gzzs_off2, -221);
    lv_obj_set_align(ui_gzzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_wxbjsgd_off2, &ui_img_525662809);
    lv_obj_set_width(ui_wxbjsgd_off2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_off2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_off2, 72);
    lv_obj_set_y(ui_wxbjsgd_off2, -198);
    lv_obj_set_align(ui_wxbjsgd_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_off2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_fdjzs_off2, &ui_img_1926959430);
    lv_obj_set_width(ui_fdjzs_off2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_off2, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_off2, -243);
    lv_obj_set_y(ui_fdjzs_off2, -221);
    lv_obj_set_align(ui_fdjzs_off2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_off2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_off2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_fdjzs_on2, &ui_img_986460666);
    lv_obj_set_width(ui_fdjzs_on2, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_on2, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_on2, -243);
    lv_obj_set_y(ui_fdjzs_on2, -221);
    lv_obj_set_align(ui_fdjzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_yon2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_abszs_yon2, &ui_img_1539047480);
    lv_obj_set_width(ui_abszs_yon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_yon2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_yon2, 205);
    lv_obj_set_y(ui_abszs_yon2, -220);
    lv_obj_set_align(ui_abszs_yon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_yon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_yon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_yon2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sszs_yon2, &ui_img_2027837687);
    lv_obj_set_width(ui_sszs_yon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_yon2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_yon2, 237);
    lv_obj_set_y(ui_sszs_yon2, -220);
    lv_obj_set_align(ui_sszs_yon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_yon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_yon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hwdzs_on2, &ui_img_1913482559);
    lv_obj_set_width(ui_hwdzs_on2, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_on2, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_on2, -171);
    lv_obj_set_y(ui_hwdzs_on2, -220);
    lv_obj_set_align(ui_hwdzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqmzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqqmzs_on2, &ui_img_457319324);
    lv_obj_set_width(ui_aqqmzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqmzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqmzs_on2, 266);
    lv_obj_set_y(ui_aqqmzs_on2, -219);
    lv_obj_set_align(ui_aqqmzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqmzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqmzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hcgzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hcgzs_on2, &ui_img_103672274);
    lv_obj_set_width(ui_hcgzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_hcgzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_hcgzs_on2, -146);
    lv_obj_set_y(ui_hcgzs_on2, -197);
    lv_obj_set_align(ui_hcgzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hcgzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hcgzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qsgzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_qsgzs_on2, &ui_img_1539048503);
    lv_obj_set_width(ui_qsgzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qsgzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qsgzs_on2, 139);
    lv_obj_set_y(ui_qsgzs_on2, -198);
    lv_obj_set_align(ui_qsgzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qsgzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qsgzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_cmzs_on2, &ui_img_1961051338);
    lv_obj_set_width(ui_cmzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_on2, -275);
    lv_obj_set_y(ui_cmzs_on2, -224);
    lv_obj_set_align(ui_cmzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_aqdzs_on2, &ui_img_457316251);
    lv_obj_set_width(ui_aqdzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_on2, 102);
    lv_obj_set_y(ui_aqdzs_on2, -199);
    lv_obj_set_align(ui_aqdzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_dczs_on2, &ui_img_1539045430);
    lv_obj_set_width(ui_dczs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_on2, 101);
    lv_obj_set_y(ui_dczs_on2, -222);
    lv_obj_set_align(ui_dczs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_tcszs_on2, &ui_img_946110558);
    lv_obj_set_width(ui_tcszs_on2, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_on2, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_on2, -145);
    lv_obj_set_y(ui_tcszs_on2, -220);
    lv_obj_set_align(ui_tcszs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zxdzs_on2, &ui_img_1539046453);
    lv_obj_set_width(ui_zxdzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_on2, -74);
    lv_obj_set_y(ui_zxdzs_on2, -220);
    lv_obj_set_align(ui_zxdzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_wxbjsgd_on2, &ui_img_2027838714);
    lv_obj_set_width(ui_wxbjsgd_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_on2, 72);
    lv_obj_set_y(ui_wxbjsgd_on2, -198);
    lv_obj_set_align(ui_wxbjsgd_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_gzzs_on2, &ui_img_1185399403);
    lv_obj_set_width(ui_gzzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_on2, 72);
    lv_obj_set_y(ui_gzzs_on2, -221);
    lv_obj_set_align(ui_gzzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_ron2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_abszs_ron2, &ui_img_1913481532);
    lv_obj_set_width(ui_abszs_ron2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_ron2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_ron2, 206);
    lv_obj_set_y(ui_abszs_ron2, -221);
    lv_obj_set_align(ui_abszs_ron2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_ron2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_ron2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cspzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_cspzs_on2, &ui_img_946109535);
    lv_obj_set_width(ui_cspzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cspzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cspzs_on2, -111);
    lv_obj_set_y(ui_cspzs_on2, -198);
    lv_obj_set_align(ui_cspzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cspzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cspzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_ron2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sszs_ron2, &ui_img_525673059);
    lv_obj_set_width(ui_sszs_ron2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_ron2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_ron2, 237);
    lv_obj_set_y(ui_sszs_ron2, -220);
    lv_obj_set_align(ui_sszs_ron2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_ron2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_ron2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zczdzs_on2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zczdzs_on2, &ui_img_457314201);
    lv_obj_set_width(ui_zczdzs_on2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zczdzs_on2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zczdzs_on2, 177);
    lv_obj_set_y(ui_zczdzs_on2, -222);
    lv_obj_set_align(ui_zczdzs_on2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zczdzs_on2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zczdzs_on2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_jon2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yjgd_jon2, &ui_img_103667151);
    lv_obj_set_width(ui_yjgd_jon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_jon2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_jon2, -205);
    lv_obj_set_y(ui_yjgd_jon2, -220);
    lv_obj_set_align(ui_yjgd_jon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_jon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_jon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_yon2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_yjgd_yon2, &ui_img_170937940);
    lv_obj_set_width(ui_yjgd_yon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_yon2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_yon2, -206);
    lv_obj_set_y(ui_yjgd_yon2, -221);
    lv_obj_set_align(ui_yjgd_yon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_yon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_yon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time2_mh = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_time2_mh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2_mh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2_mh, -17);
    lv_obj_set_y(ui_time2_mh, -220);
    lv_obj_set_align(ui_time2_mh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2_mh, ":");
    lv_obj_set_style_text_color(ui_time2_mh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2_mh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2_mh, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time2_min = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_time2_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2_min, -1);
    lv_obj_set_y(ui_time2_min, -220);
    lv_obj_set_align(ui_time2_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2_min, "00");
    lv_obj_set_style_text_color(ui_time2_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2_min, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
