// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_bg4, &ui_img_1342356983);
    lv_obj_set_width(ui_bg4, LV_SIZE_CONTENT);   /// 815
    lv_obj_set_height(ui_bg4, LV_SIZE_CONTENT);    /// 281
    lv_obj_set_x(ui_bg4, -1);
    lv_obj_set_y(ui_bg4, 198);
    lv_obj_set_align(ui_bg4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zzd_off4, &ui_img_896079304);
    lv_obj_set_width(ui_zzd_off4, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_off4, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_off4, -361);
    lv_obj_set_y(ui_zzd_off4, -209);
    lv_obj_set_align(ui_zzd_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yzd_off4, &ui_img_1642931740);
    lv_obj_set_width(ui_yzd_off4, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_off4, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_off4, 361);
    lv_obj_set_y(ui_yzd_off4, -209);
    lv_obj_set_align(ui_yzd_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zzd_on4, &ui_img_896081354);
    lv_obj_set_width(ui_zzd_on4, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_on4, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_on4, -361);
    lv_obj_set_y(ui_zzd_on4, -209);
    lv_obj_set_align(ui_zzd_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_on4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yzd_on4, &ui_img_896082379);
    lv_obj_set_width(ui_yzd_on4, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_on4, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_on4, 361);
    lv_obj_set_y(ui_yzd_on4, -209);
    lv_obj_set_align(ui_yzd_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_on4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yhbmp4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yhbmp4, &ui_img_999003654);
    lv_obj_set_width(ui_yhbmp4, LV_SIZE_CONTENT);   /// 649
    lv_obj_set_height(ui_yhbmp4, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_yhbmp4, 2);
    lv_obj_set_y(ui_yhbmp4, -194);
    lv_obj_set_align(ui_yhbmp4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yhbmp4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yhbmp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp7 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sxbmp7, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp7, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp7, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp7, -54);
    lv_obj_set_y(ui_sxbmp7, -210);
    lv_obj_set_align(ui_sxbmp7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp8 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sxbmp8, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp8, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp8, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp8, 54);
    lv_obj_set_y(ui_sxbmp8, -210);
    lv_obj_set_align(ui_sxbmp8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time4_hour = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_time4_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time4_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time4_hour, -32);
    lv_obj_set_y(ui_time4_hour, -220);
    lv_obj_set_align(ui_time4_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time4_hour, "00");
    lv_obj_set_style_text_color(ui_time4_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time4_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time4_hour, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_date4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date4, 0);
    lv_obj_set_y(ui_date4, -198);
    lv_obj_set_align(ui_date4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date4, "2024年12月22日");
    lv_obj_set_style_text_color(ui_date4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date4, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tem4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_tem4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tem4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tem4, 25);
    lv_obj_set_y(ui_tem4, -217);
    lv_obj_set_align(ui_tem4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tem4, "00");
    lv_obj_set_style_text_color(ui_tem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tem4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tem4, &ui_font_ssd, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssd4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_ssd4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssd4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssd4, 42);
    lv_obj_set_y(ui_ssd4, -216);
    lv_obj_set_align(ui_ssd4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssd4, "℃");
    lv_obj_set_style_text_color(ui_ssd4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssd4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssd4, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mbx4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_mbx4, &ui_img_95555192);
    lv_obj_set_width(ui_mbx4, LV_SIZE_CONTENT);   /// 294
    lv_obj_set_height(ui_mbx4, LV_SIZE_CONTENT);    /// 290
    lv_obj_set_x(ui_mbx4, -264);
    lv_obj_set_y(ui_mbx4, 110);
    lv_obj_set_align(ui_mbx4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbx4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mbx4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mbs4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_mbs4, &ui_img_1870684104);
    lv_obj_set_width(ui_mbs4, LV_SIZE_CONTENT);   /// 296
    lv_obj_set_height(ui_mbs4, LV_SIZE_CONTENT);    /// 321
    lv_obj_set_x(ui_mbs4, -264);
    lv_obj_set_y(ui_mbs4, -29);
    lv_obj_set_align(ui_mbs4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mbs4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mbs4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedbig5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_speedbig5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig5, -274);
    lv_obj_set_y(ui_speedbig5, -78);
    lv_obj_set_align(ui_speedbig5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig5, "240");
    lv_obj_set_style_text_color(ui_speedbig5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig5, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig5, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig5, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedbig6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_speedbig6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedbig6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedbig6, -279);
    lv_obj_set_y(ui_speedbig6, -83);
    lv_obj_set_align(ui_speedbig6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedbig6, "240");
    lv_obj_set_style_text_color(ui_speedbig6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedbig6, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_speedbig6, -4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speedbig6, -100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedbig6, &ui_font_LCDbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_mode5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode5, -324);
    lv_obj_set_y(ui_mode5, 138);
    lv_obj_set_align(ui_mode5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode5, "P");
    lv_obj_set_style_text_color(ui_mode5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode5, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_mode6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mode6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mode6, -330);
    lv_obj_set_y(ui_mode6, 134);
    lv_obj_set_align(ui_mode6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mode6, "P");
    lv_obj_set_style_text_color(ui_mode6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode6, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode6, &ui_font_LCDbbig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mode6, lv_color_hex(0xFBD96B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mode6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_kmh5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh5, -213);
    lv_obj_set_y(ui_kmh5, 2);
    lv_obj_set_align(ui_kmh5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh5, "km/h");
    lv_obj_set_style_text_color(ui_kmh5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh5, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh5, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_kmh6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmh6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh6, -216);
    lv_obj_set_y(ui_kmh6, 0);
    lv_obj_set_align(ui_kmh6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh6, "km/h");
    lv_obj_set_style_text_color(ui_kmh6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh6, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_kmh6, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kmh6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh6, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller4 = lv_roller_create(ui_Screen4);
    lv_roller_set_options(ui_Roller4, "经济模式\n运动模式\n环保模式", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller4, 70);
    lv_obj_set_width(ui_Roller4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller4, -210);
    lv_obj_set_y(ui_Roller4, 163);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller4, lv_color_hex(0xD2D2D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller4, &ui_font_myfond__5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller4, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Roller4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Roller4, &ui_font_myfond__4, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller4, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_hgbmp9 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hgbmp9, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp9, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp9, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp9, -210);
    lv_obj_set_y(ui_hgbmp9, 148);
    lv_obj_set_align(ui_hgbmp9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp9, 135);

    ui_hgbmp10 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hgbmp10, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp10, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp10, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp10, -210);
    lv_obj_set_y(ui_hgbmp10, 176);
    lv_obj_set_align(ui_hgbmp10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp10, 135);

    ui_hgbmp11 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hgbmp11, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp11, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp11, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp11, -212);
    lv_obj_set_y(ui_hgbmp11, 131);
    lv_obj_set_align(ui_hgbmp11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp11, 110);

    ui_hgbmp12 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hgbmp12, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp12, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp12, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp12, -211);
    lv_obj_set_y(ui_hgbmp12, 194);
    lv_obj_set_align(ui_hgbmp12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_hgbmp12, 110);

    ui_cmzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_cmzs_off4, &ui_img_525677159);
    lv_obj_set_width(ui_cmzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_off4, -275);
    lv_obj_set_y(ui_cmzs_off4, -224);
    lv_obj_set_align(ui_cmzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ecozs_off4, &ui_img_1717054016);
    lv_obj_set_width(ui_ecozs_off4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_off4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_off4, -75);
    lv_obj_set_y(ui_ecozs_off4, -197);
    lv_obj_set_align(ui_ecozs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ecozs_on4, &ui_img_eco_png);
    lv_obj_set_width(ui_ecozs_on4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_on4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_on4, -75);
    lv_obj_set_y(ui_ecozs_on4, -197);
    lv_obj_set_align(ui_ecozs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_off2_3 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_skdzs_off2_3, &ui_img_1837894125);
    lv_obj_set_width(ui_skdzs_off2_3, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_off2_3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_off2_3, -110);
    lv_obj_set_y(ui_skdzs_off2_3, -221);
    lv_obj_set_align(ui_skdzs_off2_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_off2_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_off2_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_skdzs_on4, &ui_img_2027284395);
    lv_obj_set_width(ui_skdzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_on4, -110);
    lv_obj_set_y(ui_skdzs_on4, -220);
    lv_obj_set_align(ui_skdzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_dczs_off4, &ui_img_2140545812);
    lv_obj_set_width(ui_dczs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_off4, 101);
    lv_obj_set_y(ui_dczs_off4, -222);
    lv_obj_set_align(ui_dczs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yyzs_off4, &ui_img_2140544787);
    lv_obj_set_width(ui_yyzs_off4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_off4, 138);
    lv_obj_set_y(ui_yyzs_off4, -222);
    lv_obj_set_align(ui_yyzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yjgdzs_off4, &ui_img_2140546837);
    lv_obj_set_width(ui_yjgdzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgdzs_off4, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_yjgdzs_off4, -205);
    lv_obj_set_y(ui_yjgdzs_off4, -221);
    lv_obj_set_align(ui_yjgdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yyzs_on4, &ui_img_946112608);
    lv_obj_set_width(ui_yyzs_on4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_on4, 138);
    lv_obj_set_y(ui_yyzs_on4, -222);
    lv_obj_set_align(ui_yyzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqnzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_aqqnzs_off4, &ui_img_103671251);
    lv_obj_set_width(ui_aqqnzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqnzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqnzs_off4, 266);
    lv_obj_set_y(ui_aqqnzs_off4, -219);
    lv_obj_set_align(ui_aqqnzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqnzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqnzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chgzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_chgzs_off4, &ui_img_624410878);
    lv_obj_set_width(ui_chgzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_chgzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_chgzs_off4, -146);
    lv_obj_set_y(ui_chgzs_off4, -197);
    lv_obj_set_align(ui_chgzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chgzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chgzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qcgzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_qcgzs_off4, &ui_img_457318301);
    lv_obj_set_width(ui_qcgzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qcgzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qcgzs_off4, 139);
    lv_obj_set_y(ui_qcgzs_off4, -198);
    lv_obj_set_align(ui_qcgzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qcgzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qcgzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_aqdzs_off4, &ui_img_1572821649);
    lv_obj_set_width(ui_aqdzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_off4, 101);
    lv_obj_set_y(ui_aqdzs_off4, -199);
    lv_obj_set_align(ui_aqdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zxdzs_off4, &ui_img_1913469232);
    lv_obj_set_width(ui_zxdzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_off4, -74);
    lv_obj_set_y(ui_zxdzs_off4, -221);
    lv_obj_set_align(ui_zxdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_abszs_off4, &ui_img_1185387103);
    lv_obj_set_width(ui_abszs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_off4, 205);
    lv_obj_set_y(ui_abszs_off4, -221);
    lv_obj_set_align(ui_abszs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scpzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_scpzs_off4, &ui_img_2027851014);
    lv_obj_set_width(ui_scpzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_scpzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_scpzs_off4, -111);
    lv_obj_set_y(ui_scpzs_off4, -198);
    lv_obj_set_align(ui_scpzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scpzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scpzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sszs_off4, &ui_img_1092003334);
    lv_obj_set_width(ui_sszs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_off4, 237);
    lv_obj_set_y(ui_sszs_off4, -220);
    lv_obj_set_align(ui_sszs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zszdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zszdzs_off4, &ui_img_1976030069);
    lv_obj_set_width(ui_zszdzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zszdzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zszdzs_off4, 177);
    lv_obj_set_y(ui_zszdzs_off4, -222);
    lv_obj_set_align(ui_zszdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zszdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zszdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qwdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_qwdzs_off4, &ui_img_103657924);
    lv_obj_set_width(ui_qwdzs_off4, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_qwdzs_off4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_qwdzs_off4, -182);
    lv_obj_set_y(ui_qwdzs_off4, -221);
    lv_obj_set_align(ui_qwdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qwdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qwdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hwdzs_off4, &ui_img_1961040061);
    lv_obj_set_width(ui_hwdzs_off4, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_off4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_off4, -171);
    lv_obj_set_y(ui_hwdzs_off4, -220);
    lv_obj_set_align(ui_hwdzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_tcszs_off4, &ui_img_1913468209);
    lv_obj_set_width(ui_tcszs_off4, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_off4, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_off4, -145);
    lv_obj_set_y(ui_tcszs_off4, -220);
    lv_obj_set_align(ui_tcszs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_gzzs_off4, &ui_img_457303951);
    lv_obj_set_width(ui_gzzs_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_off4, 72);
    lv_obj_set_y(ui_gzzs_off4, -221);
    lv_obj_set_align(ui_gzzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_wxbjsgd_off4, &ui_img_525662809);
    lv_obj_set_width(ui_wxbjsgd_off4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_off4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_off4, 72);
    lv_obj_set_y(ui_wxbjsgd_off4, -198);
    lv_obj_set_align(ui_wxbjsgd_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_off4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_fdjzs_off4, &ui_img_1926959430);
    lv_obj_set_width(ui_fdjzs_off4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_off4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_off4, -243);
    lv_obj_set_y(ui_fdjzs_off4, -221);
    lv_obj_set_align(ui_fdjzs_off4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_off4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_off4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_fdjzs_on4, &ui_img_986460666);
    lv_obj_set_width(ui_fdjzs_on4, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_on4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_on4, -243);
    lv_obj_set_y(ui_fdjzs_on4, -221);
    lv_obj_set_align(ui_fdjzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_yon4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_abszs_yon4, &ui_img_1539047480);
    lv_obj_set_width(ui_abszs_yon4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_yon4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_yon4, 205);
    lv_obj_set_y(ui_abszs_yon4, -220);
    lv_obj_set_align(ui_abszs_yon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_yon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_yon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_yon4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sszs_yon4, &ui_img_2027837687);
    lv_obj_set_width(ui_sszs_yon4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_yon4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_yon4, 237);
    lv_obj_set_y(ui_sszs_yon4, -220);
    lv_obj_set_align(ui_sszs_yon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_yon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_yon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hwdzs_on4, &ui_img_1913482559);
    lv_obj_set_width(ui_hwdzs_on4, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_on4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_on4, -171);
    lv_obj_set_y(ui_hwdzs_on4, -220);
    lv_obj_set_align(ui_hwdzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqmzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_aqqmzs_on4, &ui_img_457319324);
    lv_obj_set_width(ui_aqqmzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqmzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqmzs_on4, 266);
    lv_obj_set_y(ui_aqqmzs_on4, -219);
    lv_obj_set_align(ui_aqqmzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqmzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqmzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hcgzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_hcgzs_on4, &ui_img_103672274);
    lv_obj_set_width(ui_hcgzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_hcgzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_hcgzs_on4, -146);
    lv_obj_set_y(ui_hcgzs_on4, -197);
    lv_obj_set_align(ui_hcgzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hcgzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hcgzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qsgzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_qsgzs_on4, &ui_img_1539048503);
    lv_obj_set_width(ui_qsgzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qsgzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qsgzs_on4, 139);
    lv_obj_set_y(ui_qsgzs_on4, -198);
    lv_obj_set_align(ui_qsgzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qsgzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qsgzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_cmzs_on4, &ui_img_1961051338);
    lv_obj_set_width(ui_cmzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_on4, -275);
    lv_obj_set_y(ui_cmzs_on4, -224);
    lv_obj_set_align(ui_cmzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_aqdzs_on4, &ui_img_457316251);
    lv_obj_set_width(ui_aqdzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_on4, 102);
    lv_obj_set_y(ui_aqdzs_on4, -199);
    lv_obj_set_align(ui_aqdzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_dczs_on4, &ui_img_1539045430);
    lv_obj_set_width(ui_dczs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_on4, 101);
    lv_obj_set_y(ui_dczs_on4, -222);
    lv_obj_set_align(ui_dczs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_tcszs_on4, &ui_img_946110558);
    lv_obj_set_width(ui_tcszs_on4, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_on4, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_on4, -145);
    lv_obj_set_y(ui_tcszs_on4, -220);
    lv_obj_set_align(ui_tcszs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zxdzs_on4, &ui_img_1539046453);
    lv_obj_set_width(ui_zxdzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_on4, -74);
    lv_obj_set_y(ui_zxdzs_on4, -220);
    lv_obj_set_align(ui_zxdzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_wxbjsgd_on4, &ui_img_2027838714);
    lv_obj_set_width(ui_wxbjsgd_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_on4, 72);
    lv_obj_set_y(ui_wxbjsgd_on4, -198);
    lv_obj_set_align(ui_wxbjsgd_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_gzzs_on4, &ui_img_1185399403);
    lv_obj_set_width(ui_gzzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_on4, 72);
    lv_obj_set_y(ui_gzzs_on4, -221);
    lv_obj_set_align(ui_gzzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_ron4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_abszs_ron4, &ui_img_1913481532);
    lv_obj_set_width(ui_abszs_ron4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_ron4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_ron4, 206);
    lv_obj_set_y(ui_abszs_ron4, -221);
    lv_obj_set_align(ui_abszs_ron4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_ron4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_ron4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cspzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_cspzs_on4, &ui_img_946109535);
    lv_obj_set_width(ui_cspzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cspzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cspzs_on4, -111);
    lv_obj_set_y(ui_cspzs_on4, -198);
    lv_obj_set_align(ui_cspzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cspzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cspzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_ron4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sszs_ron4, &ui_img_525673059);
    lv_obj_set_width(ui_sszs_ron4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_ron4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_ron4, 237);
    lv_obj_set_y(ui_sszs_ron4, -220);
    lv_obj_set_align(ui_sszs_ron4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_ron4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_ron4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zczdzs_on4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zczdzs_on4, &ui_img_457314201);
    lv_obj_set_width(ui_zczdzs_on4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zczdzs_on4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zczdzs_on4, 177);
    lv_obj_set_y(ui_zczdzs_on4, -222);
    lv_obj_set_align(ui_zczdzs_on4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zczdzs_on4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zczdzs_on4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_jon4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yjgd_jon4, &ui_img_103667151);
    lv_obj_set_width(ui_yjgd_jon4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_jon4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_jon4, -205);
    lv_obj_set_y(ui_yjgd_jon4, -220);
    lv_obj_set_align(ui_yjgd_jon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_jon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_jon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_yon4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_yjgd_yon4, &ui_img_170937940);
    lv_obj_set_width(ui_yjgd_yon4, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_yon4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_yon4, -206);
    lv_obj_set_y(ui_yjgd_yon4, -221);
    lv_obj_set_align(ui_yjgd_yon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_yon4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_yon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshilicbmp = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_xingshilicbmp, &ui_img_95451801);
    lv_obj_set_width(ui_xingshilicbmp, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_xingshilicbmp, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_xingshilicbmp, -51);
    lv_obj_set_y(ui_xingshilicbmp, -72);
    lv_obj_set_align(ui_xingshilicbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xingshilicbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_xingshilicbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshisjbmp = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_xingshisjbmp, &ui_img_999005704);
    lv_obj_set_width(ui_xingshisjbmp, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_xingshisjbmp, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_xingshisjbmp, 124);
    lv_obj_set_y(ui_xingshisjbmp, -72);
    lv_obj_set_align(ui_xingshisjbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xingshisjbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_xingshisjbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshiyouhao = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_xingshiyouhao, &ui_img_457315224);
    lv_obj_set_width(ui_xingshiyouhao, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_xingshiyouhao, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_xingshiyouhao, 298);
    lv_obj_set_y(ui_xingshiyouhao, -72);
    lv_obj_set_align(ui_xingshiyouhao, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xingshiyouhao, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_xingshiyouhao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image40 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image40, &ui_img_1482924002);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 355
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Image40, 125);
    lv_obj_set_y(ui_Image40, -128);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image41 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image41, &ui_img_km_png);
    lv_obj_set_width(ui_Image41, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image41, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image41, -51);
    lv_obj_set_y(ui_Image41, 129);
    lv_obj_set_align(ui_Image41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image41, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image42 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image42, &ui_img_h_png);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image42, 124);
    lv_obj_set_y(ui_Image42, 129);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image43 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image43, &ui_img_100km_png);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_Image43, 298);
    lv_obj_set_y(ui_Image43, 129);
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 124);
    lv_obj_set_y(ui_Label7, -128);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "本次行驶");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_myfond__2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshilicconer = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_xingshilicconer);
    lv_obj_set_width(ui_xingshilicconer, 100);
    lv_obj_set_height(ui_xingshilicconer, 50);
    lv_obj_set_x(ui_xingshilicconer, -51);
    lv_obj_set_y(ui_xingshilicconer, 27);
    lv_obj_set_align(ui_xingshilicconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_xingshilicconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_xingshilicconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_xingshilicconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshilic_value = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_xingshilic_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshilic_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshilic_value, -51);
    lv_obj_set_y(ui_xingshilic_value, 27);
    lv_obj_set_align(ui_xingshilic_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshilic_value, "9999");
    lv_obj_set_style_text_color(ui_xingshilic_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshilic_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshilic_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshisjconer = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_xingshisjconer);
    lv_obj_set_width(ui_xingshisjconer, 132);
    lv_obj_set_height(ui_xingshisjconer, 50);
    lv_obj_set_x(ui_xingshisjconer, 124);
    lv_obj_set_y(ui_xingshisjconer, 27);
    lv_obj_set_align(ui_xingshisjconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_xingshisjconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_xingshisjconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_xingshisjconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshisjh_value = lv_label_create(ui_xingshisjconer);
    lv_obj_set_width(ui_xingshisjh_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshisjh_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshisjh_value, 96);
    lv_obj_set_y(ui_xingshisjh_value, 27);
    lv_obj_set_align(ui_xingshisjh_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshisjh_value, "999");
    lv_obj_set_style_text_color(ui_xingshisjh_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshisjh_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshisjh_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshisjmh = lv_label_create(ui_xingshisjconer);
    lv_obj_set_width(ui_xingshisjmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshisjmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshisjmh, 134);
    lv_obj_set_y(ui_xingshisjmh, 27);
    lv_obj_set_align(ui_xingshisjmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshisjmh, ":");
    lv_obj_set_style_text_color(ui_xingshisjmh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshisjmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshisjmh, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshisjm_value = lv_label_create(ui_xingshisjconer);
    lv_obj_set_width(ui_xingshisjm_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshisjm_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshisjm_value, 160);
    lv_obj_set_y(ui_xingshisjm_value, 27);
    lv_obj_set_align(ui_xingshisjm_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshisjm_value, "99");
    lv_obj_set_style_text_color(ui_xingshisjm_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshisjm_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshisjm_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshiyouhaoconer = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_xingshiyouhaoconer);
    lv_obj_set_width(ui_xingshiyouhaoconer, 100);
    lv_obj_set_height(ui_xingshiyouhaoconer, 50);
    lv_obj_set_x(ui_xingshiyouhaoconer, 298);
    lv_obj_set_y(ui_xingshiyouhaoconer, 27);
    lv_obj_set_align(ui_xingshiyouhaoconer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_xingshiyouhaoconer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_xingshiyouhaoconer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_xingshiyouhaoconer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xingshiyouhaoL_value = lv_label_create(ui_xingshiyouhaoconer);
    lv_obj_set_width(ui_xingshiyouhaoL_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshiyouhaoL_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshiyouhaoL_value, 262);
    lv_obj_set_y(ui_xingshiyouhaoL_value, 27);
    lv_obj_set_align(ui_xingshiyouhaoL_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshiyouhaoL_value, "99");
    lv_obj_set_style_text_color(ui_xingshiyouhaoL_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshiyouhaoL_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshiyouhaoL_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xinshiyouhaod = lv_label_create(ui_xingshiyouhaoconer);
    lv_obj_set_width(ui_xinshiyouhaod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xinshiyouhaod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xinshiyouhaod, 303);
    lv_obj_set_y(ui_xinshiyouhaod, 27);
    lv_obj_set_align(ui_xinshiyouhaod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xinshiyouhaod, ".");
    lv_obj_set_style_text_color(ui_xinshiyouhaod, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xinshiyouhaod, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xinshiyouhaod, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshiyouhaodL_value = lv_label_create(ui_xingshiyouhaoconer);
    lv_obj_set_width(ui_xingshiyouhaodL_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshiyouhaodL_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshiyouhaodL_value, 340);
    lv_obj_set_y(ui_xingshiyouhaodL_value, 27);
    lv_obj_set_align(ui_xingshiyouhaodL_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xingshiyouhaodL_value, "99");
    lv_obj_set_style_text_color(ui_xingshiyouhaodL_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshiyouhaodL_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshiyouhaodL_value, &ui_font_LCDsmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time4_mh = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_time4_mh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time4_mh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time4_mh, -17);
    lv_obj_set_y(ui_time4_mh, -220);
    lv_obj_set_align(ui_time4_mh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time4_mh, ":");
    lv_obj_set_style_text_color(ui_time4_mh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time4_mh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time4_mh, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time4_min = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_time4_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time4_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time4_min, -1);
    lv_obj_set_y(ui_time4_min, -220);
    lv_obj_set_align(ui_time4_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time4_min, "00");
    lv_obj_set_style_text_color(ui_time4_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time4_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time4_min, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}
