// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_bg1, &ui_img_1342356983);
    lv_obj_set_width(ui_bg1, LV_SIZE_CONTENT);   /// 815
    lv_obj_set_height(ui_bg1, LV_SIZE_CONTENT);    /// 281
    lv_obj_set_x(ui_bg1, -1);
    lv_obj_set_y(ui_bg1, 198);
    lv_obj_set_align(ui_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_daolubmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_daolubmp, &ui_img_851353715);
    lv_obj_set_width(ui_daolubmp, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_daolubmp, LV_SIZE_CONTENT);    /// 156
    lv_obj_set_x(ui_daolubmp, 2);
    lv_obj_set_y(ui_daolubmp, 186);
    lv_obj_set_align(ui_daolubmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_daolubmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_daolubmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chRoller2 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_chRoller2, "经济模式\n运动模式\n环保模式", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_chRoller2, 1, LV_ANIM_OFF);
    lv_obj_set_height(ui_chRoller2, 86);
    lv_obj_set_width(ui_chRoller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_chRoller2, -5);
    lv_obj_set_y(ui_chRoller2, -112);
    lv_obj_set_align(ui_chRoller2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_chRoller2, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chRoller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_chRoller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_chRoller2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chRoller2, &ui_font_myfond__4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chRoller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chRoller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_chRoller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_chRoller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_chRoller2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chRoller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chRoller2, &ui_font_myfond__3, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chRoller2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chRoller2, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_zzd_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zzd_off1, &ui_img_896079304);
    lv_obj_set_width(ui_zzd_off1, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_off1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_off1, -361);
    lv_obj_set_y(ui_zzd_off1, -209);
    lv_obj_set_align(ui_zzd_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yzd_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yzd_off1, &ui_img_1642931740);
    lv_obj_set_width(ui_yzd_off1, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_off1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_off1, 361);
    lv_obj_set_y(ui_yzd_off1, -209);
    lv_obj_set_align(ui_yzd_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_off1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zzd_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zzd_on1, &ui_img_896081354);
    lv_obj_set_width(ui_zzd_on1, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_zzd_on1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_zzd_on1, -361);
    lv_obj_set_y(ui_zzd_on1, -209);
    lv_obj_set_align(ui_zzd_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zzd_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zzd_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_zzd_on1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_zzd_on1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yzd_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yzd_on1, &ui_img_896082379);
    lv_obj_set_width(ui_yzd_on1, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yzd_on1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_yzd_on1, 361);
    lv_obj_set_y(ui_yzd_on1, -209);
    lv_obj_set_align(ui_yzd_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yzd_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yzd_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yhbmp1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yhbmp1, &ui_img_999003654);
    lv_obj_set_width(ui_yhbmp1, LV_SIZE_CONTENT);   /// 649
    lv_obj_set_height(ui_yhbmp1, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_yhbmp1, 2);
    lv_obj_set_y(ui_yhbmp1, -194);
    lv_obj_set_align(ui_yhbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yhbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yhbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sxbmp1, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp1, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp1, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp1, -54);
    lv_obj_set_y(ui_sxbmp1, -210);
    lv_obj_set_align(ui_sxbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sxbmp2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sxbmp2, &ui_img_1995059043);
    lv_obj_set_width(ui_sxbmp2, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_sxbmp2, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_sxbmp2, 54);
    lv_obj_set_y(ui_sxbmp2, -210);
    lv_obj_set_align(ui_sxbmp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sxbmp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sxbmp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time1_hour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time1_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1_hour, -32);
    lv_obj_set_y(ui_time1_hour, -220);
    lv_obj_set_align(ui_time1_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1_hour, "00");
    lv_obj_set_style_text_color(ui_time1_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1_hour, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date1, 0);
    lv_obj_set_y(ui_date1, -198);
    lv_obj_set_align(ui_date1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date1, "2024年12月22日");
    lv_obj_set_style_text_color(ui_date1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date1, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tem1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tem1, 25);
    lv_obj_set_y(ui_tem1, -217);
    lv_obj_set_align(ui_tem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tem1, "00");
    lv_obj_set_style_text_color(ui_tem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tem1, &ui_font_ssd, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssd1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ssd1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssd1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssd1, 42);
    lv_obj_set_y(ui_ssd1, -216);
    lv_obj_set_align(ui_ssd1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssd1, "℃");
    lv_obj_set_style_text_color(ui_ssd1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssd1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssd1, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cmzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cmzs_off1, &ui_img_525677159);
    lv_obj_set_width(ui_cmzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_off1, -275);
    lv_obj_set_y(ui_cmzs_off1, -224);
    lv_obj_set_align(ui_cmzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ecozs_off1, &ui_img_1717054016);
    lv_obj_set_width(ui_ecozs_off1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_off1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_off1, -75);
    lv_obj_set_y(ui_ecozs_off1, -197);
    lv_obj_set_align(ui_ecozs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ecozs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ecozs_on1, &ui_img_eco_png);
    lv_obj_set_width(ui_ecozs_on1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_ecozs_on1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_ecozs_on1, -75);
    lv_obj_set_y(ui_ecozs_on1, -197);
    lv_obj_set_align(ui_ecozs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecozs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ecozs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_off2_1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_skdzs_off2_1, &ui_img_1837894125);
    lv_obj_set_width(ui_skdzs_off2_1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_off2_1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_off2_1, -110);
    lv_obj_set_y(ui_skdzs_off2_1, -221);
    lv_obj_set_align(ui_skdzs_off2_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_off2_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_off2_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_skdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_skdzs_on1, &ui_img_2027284395);
    lv_obj_set_width(ui_skdzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_skdzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_skdzs_on1, -110);
    lv_obj_set_y(ui_skdzs_on1, -220);
    lv_obj_set_align(ui_skdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_dczs_off1, &ui_img_2140545812);
    lv_obj_set_width(ui_dczs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_off1, 101);
    lv_obj_set_y(ui_dczs_off1, -222);
    lv_obj_set_align(ui_dczs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yyzs_off1, &ui_img_2140544787);
    lv_obj_set_width(ui_yyzs_off1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_off1, 138);
    lv_obj_set_y(ui_yyzs_off1, -222);
    lv_obj_set_align(ui_yyzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yjgdzs_off1, &ui_img_2140546837);
    lv_obj_set_width(ui_yjgdzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgdzs_off1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_yjgdzs_off1, -205);
    lv_obj_set_y(ui_yjgdzs_off1, -221);
    lv_obj_set_align(ui_yjgdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yyzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yyzs_on1, &ui_img_946112608);
    lv_obj_set_width(ui_yyzs_on1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_yyzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yyzs_on1, 138);
    lv_obj_set_y(ui_yyzs_on1, -222);
    lv_obj_set_align(ui_yyzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yyzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yyzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqnzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_aqqnzs_off1, &ui_img_103671251);
    lv_obj_set_width(ui_aqqnzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqnzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqnzs_off1, 266);
    lv_obj_set_y(ui_aqqnzs_off1, -219);
    lv_obj_set_align(ui_aqqnzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqnzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqnzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chgzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_chgzs_off1, &ui_img_624410878);
    lv_obj_set_width(ui_chgzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_chgzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_chgzs_off1, -146);
    lv_obj_set_y(ui_chgzs_off1, -197);
    lv_obj_set_align(ui_chgzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chgzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chgzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qcgzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_qcgzs_off1, &ui_img_457318301);
    lv_obj_set_width(ui_qcgzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qcgzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qcgzs_off1, 139);
    lv_obj_set_y(ui_qcgzs_off1, -198);
    lv_obj_set_align(ui_qcgzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qcgzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qcgzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_aqdzs_off1, &ui_img_1572821649);
    lv_obj_set_width(ui_aqdzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_off1, 101);
    lv_obj_set_y(ui_aqdzs_off1, -199);
    lv_obj_set_align(ui_aqdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zxdzs_off1, &ui_img_1913469232);
    lv_obj_set_width(ui_zxdzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_off1, -74);
    lv_obj_set_y(ui_zxdzs_off1, -221);
    lv_obj_set_align(ui_zxdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_abszs_off1, &ui_img_1185387103);
    lv_obj_set_width(ui_abszs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_off1, 205);
    lv_obj_set_y(ui_abszs_off1, -221);
    lv_obj_set_align(ui_abszs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scpzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_scpzs_off1, &ui_img_2027851014);
    lv_obj_set_width(ui_scpzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_scpzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_scpzs_off1, -111);
    lv_obj_set_y(ui_scpzs_off1, -198);
    lv_obj_set_align(ui_scpzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scpzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scpzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sszs_off1, &ui_img_1092003334);
    lv_obj_set_width(ui_sszs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_off1, 237);
    lv_obj_set_y(ui_sszs_off1, -220);
    lv_obj_set_align(ui_sszs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zszdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zszdzs_off1, &ui_img_1976030069);
    lv_obj_set_width(ui_zszdzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zszdzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zszdzs_off1, 177);
    lv_obj_set_y(ui_zszdzs_off1, -222);
    lv_obj_set_align(ui_zszdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zszdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zszdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qwdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_qwdzs_off1, &ui_img_103657924);
    lv_obj_set_width(ui_qwdzs_off1, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_qwdzs_off1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_qwdzs_off1, -182);
    lv_obj_set_y(ui_qwdzs_off1, -221);
    lv_obj_set_align(ui_qwdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qwdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qwdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hwdzs_off1, &ui_img_1961040061);
    lv_obj_set_width(ui_hwdzs_off1, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_off1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_off1, -171);
    lv_obj_set_y(ui_hwdzs_off1, -220);
    lv_obj_set_align(ui_hwdzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tcszs_off1, &ui_img_1913468209);
    lv_obj_set_width(ui_tcszs_off1, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_off1, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_off1, -145);
    lv_obj_set_y(ui_tcszs_off1, -220);
    lv_obj_set_align(ui_tcszs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gzzs_off1, &ui_img_457303951);
    lv_obj_set_width(ui_gzzs_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_off1, 72);
    lv_obj_set_y(ui_gzzs_off1, -221);
    lv_obj_set_align(ui_gzzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wxbjsgd_off1, &ui_img_525662809);
    lv_obj_set_width(ui_wxbjsgd_off1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_off1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_off1, 72);
    lv_obj_set_y(ui_wxbjsgd_off1, -198);
    lv_obj_set_align(ui_wxbjsgd_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_off1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fdjzs_off1, &ui_img_1926959430);
    lv_obj_set_width(ui_fdjzs_off1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_off1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_off1, -243);
    lv_obj_set_y(ui_fdjzs_off1, -221);
    lv_obj_set_align(ui_fdjzs_off1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_off1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_off1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fdjzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fdjzs_on1, &ui_img_986460666);
    lv_obj_set_width(ui_fdjzs_on1, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_fdjzs_on1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_fdjzs_on1, -243);
    lv_obj_set_y(ui_fdjzs_on1, -221);
    lv_obj_set_align(ui_fdjzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fdjzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fdjzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_yon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_abszs_yon1, &ui_img_1539047480);
    lv_obj_set_width(ui_abszs_yon1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_yon1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_yon1, 205);
    lv_obj_set_y(ui_abszs_yon1, -220);
    lv_obj_set_align(ui_abszs_yon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_yon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_yon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_yon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sszs_yon1, &ui_img_2027837687);
    lv_obj_set_width(ui_sszs_yon1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_yon1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_yon1, 237);
    lv_obj_set_y(ui_sszs_yon1, -220);
    lv_obj_set_align(ui_sszs_yon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_yon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_yon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hwdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hwdzs_on1, &ui_img_1913482559);
    lv_obj_set_width(ui_hwdzs_on1, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_hwdzs_on1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_hwdzs_on1, -171);
    lv_obj_set_y(ui_hwdzs_on1, -220);
    lv_obj_set_align(ui_hwdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hwdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hwdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqqmzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_aqqmzs_on1, &ui_img_457319324);
    lv_obj_set_width(ui_aqqmzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqqmzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqqmzs_on1, 266);
    lv_obj_set_y(ui_aqqmzs_on1, -219);
    lv_obj_set_align(ui_aqqmzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqqmzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqqmzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hcgzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hcgzs_on1, &ui_img_103672274);
    lv_obj_set_width(ui_hcgzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_hcgzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_hcgzs_on1, -146);
    lv_obj_set_y(ui_hcgzs_on1, -197);
    lv_obj_set_align(ui_hcgzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hcgzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hcgzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qsgzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_qsgzs_on1, &ui_img_1539048503);
    lv_obj_set_width(ui_qsgzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_qsgzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_qsgzs_on1, 139);
    lv_obj_set_y(ui_qsgzs_on1, -198);
    lv_obj_set_align(ui_qsgzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qsgzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qsgzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cmzs_on1, &ui_img_1961051338);
    lv_obj_set_width(ui_cmzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cmzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cmzs_on1, -275);
    lv_obj_set_y(ui_cmzs_on1, -224);
    lv_obj_set_align(ui_cmzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aqdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_aqdzs_on1, &ui_img_457316251);
    lv_obj_set_width(ui_aqdzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_aqdzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_aqdzs_on1, 102);
    lv_obj_set_y(ui_aqdzs_on1, -199);
    lv_obj_set_align(ui_aqdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aqdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aqdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dczs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_dczs_on1, &ui_img_1539045430);
    lv_obj_set_width(ui_dczs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_dczs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_dczs_on1, 101);
    lv_obj_set_y(ui_dczs_on1, -222);
    lv_obj_set_align(ui_dczs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dczs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dczs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tcszs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tcszs_on1, &ui_img_946110558);
    lv_obj_set_width(ui_tcszs_on1, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_tcszs_on1, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_tcszs_on1, -145);
    lv_obj_set_y(ui_tcszs_on1, -220);
    lv_obj_set_align(ui_tcszs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tcszs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tcszs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zxdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zxdzs_on1, &ui_img_1539046453);
    lv_obj_set_width(ui_zxdzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zxdzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zxdzs_on1, -74);
    lv_obj_set_y(ui_zxdzs_on1, -220);
    lv_obj_set_align(ui_zxdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zxdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zxdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wxbjsgd_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wxbjsgd_on1, &ui_img_2027838714);
    lv_obj_set_width(ui_wxbjsgd_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_wxbjsgd_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wxbjsgd_on1, 72);
    lv_obj_set_y(ui_wxbjsgd_on1, -198);
    lv_obj_set_align(ui_wxbjsgd_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wxbjsgd_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wxbjsgd_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gzzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gzzs_on1, &ui_img_1185399403);
    lv_obj_set_width(ui_gzzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_gzzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_gzzs_on1, 72);
    lv_obj_set_y(ui_gzzs_on1, -221);
    lv_obj_set_align(ui_gzzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gzzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gzzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_abszs_ron1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_abszs_ron1, &ui_img_1913481532);
    lv_obj_set_width(ui_abszs_ron1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_abszs_ron1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_abszs_ron1, 206);
    lv_obj_set_y(ui_abszs_ron1, -221);
    lv_obj_set_align(ui_abszs_ron1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_abszs_ron1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_abszs_ron1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cspzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cspzs_on1, &ui_img_946109535);
    lv_obj_set_width(ui_cspzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_cspzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_cspzs_on1, -111);
    lv_obj_set_y(ui_cspzs_on1, -198);
    lv_obj_set_align(ui_cspzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cspzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cspzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sszs_ron1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sszs_ron1, &ui_img_525673059);
    lv_obj_set_width(ui_sszs_ron1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_sszs_ron1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_sszs_ron1, 237);
    lv_obj_set_y(ui_sszs_ron1, -220);
    lv_obj_set_align(ui_sszs_ron1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sszs_ron1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sszs_ron1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zczdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_zczdzs_on1, &ui_img_457314201);
    lv_obj_set_width(ui_zczdzs_on1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_zczdzs_on1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_zczdzs_on1, 177);
    lv_obj_set_y(ui_zczdzs_on1, -222);
    lv_obj_set_align(ui_zczdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zczdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zczdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_jon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yjgd_jon1, &ui_img_103667151);
    lv_obj_set_width(ui_yjgd_jon1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_jon1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_jon1, -205);
    lv_obj_set_y(ui_yjgd_jon1, -220);
    lv_obj_set_align(ui_yjgd_jon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_jon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_jon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yjgd_yon1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yjgd_yon1, &ui_img_170937940);
    lv_obj_set_width(ui_yjgd_yon1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_yjgd_yon1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yjgd_yon1, -206);
    lv_obj_set_y(ui_yjgd_yon1, -221);
    lv_obj_set_align(ui_yjgd_yon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yjgd_yon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yjgd_yon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speed_num_view = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speed_num_view, &ui_img_170934617);
    lv_obj_set_width(ui_speed_num_view, LV_SIZE_CONTENT);   /// 267
    lv_obj_set_height(ui_speed_num_view, LV_SIZE_CONTENT);    /// 210
    lv_obj_set_x(ui_speed_num_view, 0);
    lv_obj_set_y(ui_speed_num_view, 13);
    lv_obj_set_align(ui_speed_num_view, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speed_num_view, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speed_num_view, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rev_view = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rev_view, &ui_img_170932567);
    lv_obj_set_width(ui_rev_view, LV_SIZE_CONTENT);   /// 369
    lv_obj_set_height(ui_rev_view, LV_SIZE_CONTENT);    /// 372
    lv_obj_set_x(ui_rev_view, -246);
    lv_obj_set_y(ui_rev_view, 26);
    lv_obj_set_align(ui_rev_view, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rev_view, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rev_view, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speed_view = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speed_view, &ui_img_1519863221);
    lv_obj_set_width(ui_speed_view, LV_SIZE_CONTENT);   /// 369
    lv_obj_set_height(ui_speed_view, LV_SIZE_CONTENT);    /// 372
    lv_obj_set_x(ui_speed_view, 246);
    lv_obj_set_y(ui_speed_view, 26);
    lv_obj_set_align(ui_speed_view, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speed_view, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speed_view, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jdtspeed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_jdtspeed, &ui_img_981208607);
    lv_obj_set_width(ui_jdtspeed, LV_SIZE_CONTENT);   /// 204
    lv_obj_set_height(ui_jdtspeed, LV_SIZE_CONTENT);    /// 155
    lv_obj_set_x(ui_jdtspeed, 244);
    lv_obj_set_y(ui_jdtspeed, 110);
    lv_obj_set_align(ui_jdtspeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jdtspeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_jdtspeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_jdtspeed, 102, 0);
    lv_img_set_angle(ui_jdtspeed, -8);

    ui_menbanspeed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_menbanspeed, &ui_img_724779459);
    lv_obj_set_width(ui_menbanspeed, LV_SIZE_CONTENT);   /// 351
    lv_obj_set_height(ui_menbanspeed, LV_SIZE_CONTENT);    /// 350
    lv_obj_set_x(ui_menbanspeed, 243);
    lv_obj_set_y(ui_menbanspeed, 33);
    lv_obj_set_align(ui_menbanspeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menbanspeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menbanspeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rev_jdt = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rev_jdt, &ui_img_981208607);
    lv_obj_set_width(ui_rev_jdt, LV_SIZE_CONTENT);   /// 204
    lv_obj_set_height(ui_rev_jdt, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_rev_jdt, -248);
    lv_obj_set_y(ui_rev_jdt, 110);
    lv_obj_set_align(ui_rev_jdt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rev_jdt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rev_jdt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_rev_jdt, 102, 0);
    lv_img_set_angle(ui_rev_jdt, -8);

    ui_menbanrev = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_menbanrev, &ui_img_769222035);
    lv_obj_set_width(ui_menbanrev, LV_SIZE_CONTENT);   /// 351
    lv_obj_set_height(ui_menbanrev, LV_SIZE_CONTENT);    /// 351
    lv_obj_set_x(ui_menbanrev, -249);
    lv_obj_set_y(ui_menbanrev, 32);
    lv_obj_set_align(ui_menbanrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menbanrev, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_menbanrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hgbmp1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hgbmp1, &ui_img_1870676681);
    lv_obj_set_width(ui_hgbmp1, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_hgbmp1, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp1, 1);
    lv_obj_set_y(ui_hgbmp1, -161);
    lv_obj_set_align(ui_hgbmp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hgbmp2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hgbmp2, &ui_img_1870676681);
    lv_obj_set_width(ui_hgbmp2, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_hgbmp2, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp2, 2);
    lv_obj_set_y(ui_hgbmp2, -70);
    lv_obj_set_align(ui_hgbmp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hgbmp3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hgbmp3, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp3, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp3, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp3, 0);
    lv_obj_set_y(ui_hgbmp3, -134);
    lv_obj_set_align(ui_hgbmp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hgbmp4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hgbmp4, &ui_img_1870682054);
    lv_obj_set_width(ui_hgbmp4, LV_SIZE_CONTENT);   /// 198
    lv_obj_set_height(ui_hgbmp4, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_hgbmp4, 1);
    lv_obj_set_y(ui_hgbmp4, -97);
    lv_obj_set_align(ui_hgbmp4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hgbmp4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hgbmp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_cat_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 107
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 106
    lv_obj_set_x(ui_Image9, 1);
    lv_obj_set_y(ui_Image9, 178);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gas_hand = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gas_hand, &ui_img_815005746);
    lv_obj_set_width(ui_gas_hand, LV_SIZE_CONTENT);   /// 94
    lv_obj_set_height(ui_gas_hand, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_gas_hand, -297);
    lv_obj_set_y(ui_gas_hand, 92);
    lv_obj_set_align(ui_gas_hand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gas_hand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gas_hand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_gas_hand, 94, 0);
    lv_img_set_angle(ui_gas_hand, -830);

    ui_tem_hand = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tem_hand, &ui_img_815005746);
    lv_obj_set_width(ui_tem_hand, LV_SIZE_CONTENT);   /// 94
    lv_obj_set_height(ui_tem_hand, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_tem_hand, 197);
    lv_obj_set_y(ui_tem_hand, 90);
    lv_obj_set_align(ui_tem_hand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tem_hand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tem_hand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_tem_hand, 94, 0);

    ui_rev_hand = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_rev_hand, &ui_img_946108508);
    lv_obj_set_width(ui_rev_hand, LV_SIZE_CONTENT);   /// 143
    lv_obj_set_height(ui_rev_hand, LV_SIZE_CONTENT);    /// 82
    lv_obj_set_x(ui_rev_hand, -293);
    lv_obj_set_y(ui_rev_hand, 56);
    lv_obj_set_align(ui_rev_hand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rev_hand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rev_hand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_rev_hand, 114, 21);

    ui_speed_hand = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_speed_hand, &ui_img_946108508);
    lv_obj_set_width(ui_speed_hand, LV_SIZE_CONTENT);   /// 143
    lv_obj_set_height(ui_speed_hand, LV_SIZE_CONTENT);    /// 82
    lv_obj_set_x(ui_speed_hand, 204);
    lv_obj_set_y(ui_speed_hand, 49);
    lv_obj_set_align(ui_speed_hand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speed_hand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speed_hand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_speed_hand, 114, 21);
    lv_img_set_angle(ui_speed_hand, -20);

    ui_speedvalue1_2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedvalue1_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedvalue1_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedvalue1_2, -4);
    lv_obj_set_y(ui_speedvalue1_2, 30);
    lv_obj_set_align(ui_speedvalue1_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedvalue1_2, "240");
    lv_obj_set_style_text_color(ui_speedvalue1_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedvalue1_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedvalue1_2, &ui_font_LCDmid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedvalue1_1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedvalue1_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedvalue1_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedvalue1_1, -7);
    lv_obj_set_y(ui_speedvalue1_1, 29);
    lv_obj_set_align(ui_speedvalue1_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedvalue1_1, "240");
    lv_obj_set_style_text_color(ui_speedvalue1_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedvalue1_1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedvalue1_1, &ui_font_LCDmid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Poffbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Poffbmp, &ui_img_1892395617);
    lv_obj_set_width(ui_Poffbmp, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_Poffbmp, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Poffbmp, -289);
    lv_obj_set_y(ui_Poffbmp, 110);
    lv_obj_set_align(ui_Poffbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Poffbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Poffbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roffbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Roffbmp, &ui_img_868676823);
    lv_obj_set_width(ui_Roffbmp, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_Roffbmp, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Roffbmp, -268);
    lv_obj_set_y(ui_Roffbmp, 110);
    lv_obj_set_align(ui_Roffbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Roffbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Roffbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Noffbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Noffbmp, &ui_img_1284881333);
    lv_obj_set_width(ui_Noffbmp, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Noffbmp, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Noffbmp, -248);
    lv_obj_set_y(ui_Noffbmp, 110);
    lv_obj_set_align(ui_Noffbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Noffbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Noffbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Doffbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Doffbmp, &ui_img_1785161219);
    lv_obj_set_width(ui_Doffbmp, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_Doffbmp, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Doffbmp, -227);
    lv_obj_set_y(ui_Doffbmp, 111);
    lv_obj_set_align(ui_Doffbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Doffbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Doffbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ponbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Ponbmp, &ui_img_p_png);
    lv_obj_set_width(ui_Ponbmp, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Ponbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Ponbmp, -289);
    lv_obj_set_y(ui_Ponbmp, 110);
    lv_obj_set_align(ui_Ponbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ponbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ponbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ronbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Ronbmp, &ui_img_r_png);
    lv_obj_set_width(ui_Ronbmp, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Ronbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Ronbmp, -268);
    lv_obj_set_y(ui_Ronbmp, 110);
    lv_obj_set_align(ui_Ronbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ronbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ronbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Nonbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Nonbmp, &ui_img_n_png);
    lv_obj_set_width(ui_Nonbmp, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Nonbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Nonbmp, -247);
    lv_obj_set_y(ui_Nonbmp, 110);
    lv_obj_set_align(ui_Nonbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Nonbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Nonbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Donbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Donbmp, &ui_img_d_png);
    lv_obj_set_width(ui_Donbmp, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Donbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Donbmp, -227);
    lv_obj_set_y(ui_Donbmp, 110);
    lv_obj_set_align(ui_Donbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Donbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Donbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Soffbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Soffbmp, &ui_img_665461724);
    lv_obj_set_width(ui_Soffbmp, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Soffbmp, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Soffbmp, -207);
    lv_obj_set_y(ui_Soffbmp, 110);
    lv_obj_set_align(ui_Soffbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Soffbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Soffbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sonbmp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Sonbmp, &ui_img_s_png);
    lv_obj_set_width(ui_Sonbmp, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Sonbmp, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_Sonbmp, -206);
    lv_obj_set_y(ui_Sonbmp, 110);
    lv_obj_set_align(ui_Sonbmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Sonbmp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Sonbmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jbzq = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_jbzq, &ui_img_1548035452);
    lv_obj_set_width(ui_jbzq, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_jbzq, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_jbzq, -48);
    lv_obj_set_y(ui_jbzq, 128);
    lv_obj_set_align(ui_jbzq, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jbzq, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_jbzq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jbyq = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_jbyq, &ui_img_1548035452);
    lv_obj_set_width(ui_jbyq, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_jbyq, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_jbyq, 48);
    lv_obj_set_y(ui_jbyq, 128);
    lv_obj_set_align(ui_jbyq, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jbyq, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_jbyq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jbzyh = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_jbzyh, &ui_img_1548035452);
    lv_obj_set_width(ui_jbzyh, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_jbzyh, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_jbzyh, 64);
    lv_obj_set_y(ui_jbzyh, 211);
    lv_obj_set_align(ui_jbzyh, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jbzyh, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_jbzyh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_jbzzh = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_jbzzh, &ui_img_1548035452);
    lv_obj_set_width(ui_jbzzh, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_jbzzh, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_jbzzh, -64);
    lv_obj_set_y(ui_jbzzh, 211);
    lv_obj_set_align(ui_jbzzh, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jbzzh, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_jbzzh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 97);
    lv_obj_set_height(ui_Container1, 53);
    lv_obj_set_x(ui_Container1, 243);
    lv_obj_set_y(ui_Container1, 107);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x484747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x70706E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zonlic_value_mini = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_zonlic_value_mini, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zonlic_value_mini, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zonlic_value_mini, -261);
    lv_obj_set_y(ui_zonlic_value_mini, 120);
    lv_obj_set_align(ui_zonlic_value_mini, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_zonlic_value_mini, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_zonlic_value_mini, "999999");
    lv_obj_set_style_text_color(ui_zonlic_value_mini, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zonlic_value_mini, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_zonlic_value_mini, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_zonlic_value_mini, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zonlic_value_mini, &ui_font_liteLCD, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_zonlic_value_mini, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_zonlic_value_mini, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_zonlic_value_mini, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xingshilic_value_mini = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_xingshilic_value_mini, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xingshilic_value_mini, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xingshilic_value_mini, -250);
    lv_obj_set_y(ui_xingshilic_value_mini, 124);
    lv_obj_set_align(ui_xingshilic_value_mini, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_xingshilic_value_mini, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_xingshilic_value_mini, "10086");
    lv_obj_set_style_text_color(ui_xingshilic_value_mini, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xingshilic_value_mini, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xingshilic_value_mini, &ui_font_liteLCD, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1_mh = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time1_mh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1_mh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1_mh, -17);
    lv_obj_set_y(ui_time1_mh, -220);
    lv_obj_set_align(ui_time1_mh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1_mh, ":");
    lv_obj_set_style_text_color(ui_time1_mh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1_mh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1_mh, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1_min = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time1_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1_min, -1);
    lv_obj_set_y(ui_time1_min, -220);
    lv_obj_set_align(ui_time1_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1_min, "00");
    lv_obj_set_style_text_color(ui_time1_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1_min, &ui_font_myfond__1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qwdzs_on1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_qwdzs_on1, &ui_img_2027840764);
    lv_obj_set_width(ui_qwdzs_on1, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_qwdzs_on1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_qwdzs_on1, -182);
    lv_obj_set_y(ui_qwdzs_on1, -220);
    lv_obj_set_align(ui_qwdzs_on1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qwdzs_on1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qwdzs_on1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gaszs_off = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gaszs_off, &ui_img_896085702);
    lv_obj_set_width(ui_gaszs_off, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_gaszs_off, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_gaszs_off, -176);
    lv_obj_set_y(ui_gaszs_off, -200);
    lv_obj_set_align(ui_gaszs_off, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gaszs_off, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gaszs_off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gaszs_on = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_gaszs_on, &ui_img_180952517);
    lv_obj_set_width(ui_gaszs_on, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_gaszs_on, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_gaszs_on, -176);
    lv_obj_set_y(ui_gaszs_on, -200);
    lv_obj_set_align(ui_gaszs_on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gaszs_on, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gaszs_on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watertemzs_off = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_watertemzs_off, &ui_img_41620303);
    lv_obj_set_width(ui_watertemzs_off, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_watertemzs_off, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_watertemzs_off, 177);
    lv_obj_set_y(ui_watertemzs_off, -200);
    lv_obj_set_align(ui_watertemzs_off, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watertemzs_off, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watertemzs_off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watertemzs_on = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_watertemzs_on, &ui_img_41619278);
    lv_obj_set_width(ui_watertemzs_on, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_watertemzs_on, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_watertemzs_on, 177);
    lv_obj_set_y(ui_watertemzs_on, -200);
    lv_obj_set_align(ui_watertemzs_on, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watertemzs_on, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watertemzs_on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
