// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_denglvjiemiantupian = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_denglvjiemiantupian, &ui_img_loadcar_png);
    lv_obj_set_width(ui_denglvjiemiantupian, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_denglvjiemiantupian, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_denglvjiemiantupian, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_denglvjiemiantupian, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_denglvjiemiantupian, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel3, 550);
    lv_obj_set_height(ui_Panel3, 330);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x181C24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel3, 102, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_denglvbiaoti = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_denglvbiaoti, 130);
    lv_obj_set_height(ui_denglvbiaoti, 50);
    lv_obj_set_align(ui_denglvbiaoti, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_denglvbiaoti, "用户登录");
    lv_obj_set_style_text_color(ui_denglvbiaoti, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_denglvbiaoti, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_denglvbiaoti, &ui_font_denglvjiemian, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fangxiangpan = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_fangxiangpan, &ui_img_fxp_png);
    lv_obj_set_width(ui_fangxiangpan, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_fangxiangpan, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_fangxiangpan, -200);
    lv_obj_set_y(ui_fangxiangpan, -60);
    lv_obj_set_align(ui_fangxiangpan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fangxiangpan, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fangxiangpan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yonghuming = lv_label_create(ui_Panel3);
    lv_obj_set_x(ui_yonghuming, -110);
    lv_obj_set_y(ui_yonghuming, -60);
    lv_obj_set_align(ui_yonghuming, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yonghuming, "用户名:");
    lv_obj_set_style_text_color(ui_yonghuming, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yonghuming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yonghuming, &ui_font_denglvjiemian, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhanghaoText = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_zhanghaoText, 200);
    lv_obj_set_height(ui_zhanghaoText, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_zhanghaoText, 50);
    lv_obj_set_y(ui_zhanghaoText, -60);
    lv_obj_set_align(ui_zhanghaoText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_zhanghaoText, "Account");
    lv_textarea_set_one_line(ui_zhanghaoText, true);
    lv_obj_set_style_text_color(ui_zhanghaoText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhanghaoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhanghaoText, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_carkey = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_carkey, &ui_img_carkey_png);
    lv_obj_set_width(ui_carkey, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_carkey, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_carkey, -200);
    lv_obj_set_y(ui_carkey, 10);
    lv_obj_set_align(ui_carkey, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_carkey, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_carkey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mima = lv_label_create(ui_Panel3);
    lv_obj_set_x(ui_mima, -110);
    lv_obj_set_y(ui_mima, 10);
    lv_obj_set_align(ui_mima, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mima, "密码:");
    lv_obj_set_style_text_color(ui_mima, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mima, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mima, &ui_font_denglvjiemian, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mimaText = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_mimaText, 200);
    lv_obj_set_height(ui_mimaText, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_mimaText, 50);
    lv_obj_set_y(ui_mimaText, 10);
    lv_obj_set_align(ui_mimaText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_mimaText, "Password");
    lv_textarea_set_one_line(ui_mimaText, true);
    lv_textarea_set_password_mode(ui_mimaText, true);
    lv_obj_set_style_text_color(ui_mimaText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mimaText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mimaText, &ui_font_date_font, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_denglvButton = lv_btn_create(ui_Panel3);
    lv_obj_add_event_cb(ui_denglvButton, denglvhanshu01, LV_EVENT_CLICKED, NULL);
    lv_obj_set_width(ui_denglvButton, 100);
    lv_obj_set_height(ui_denglvButton, 50);
    lv_obj_set_x(ui_denglvButton, -130);
    lv_obj_set_y(ui_denglvButton, 100);
    lv_obj_set_align(ui_denglvButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_denglvButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_denglvButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_denglvButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_denglvButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_denglv = lv_label_create(ui_denglvButton);
    lv_obj_set_width(ui_denglv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_denglv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_denglv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_denglv, "登录");
    lv_obj_set_style_text_color(ui_denglv, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_denglv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_denglv, &ui_font_denglvjiemian, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuceButton = lv_btn_create(ui_Panel3);
    lv_obj_add_event_cb(ui_zhuceButton, zhucehanshu01, LV_EVENT_CLICKED, NULL);
    lv_obj_set_width(ui_zhuceButton, 100);
    lv_obj_set_height(ui_zhuceButton, 50);
    lv_obj_set_x(ui_zhuceButton, 130);
    lv_obj_set_y(ui_zhuceButton, 100);
    lv_obj_set_align(ui_zhuceButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuceButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuceButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_zhuce = lv_label_create(ui_zhuceButton);
    lv_obj_set_width(ui_zhuce, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zhuce, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_zhuce, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhuce, "注册");
    lv_obj_set_style_text_color(ui_zhuce, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhuce, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhuce, &ui_font_denglvjiemian, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen5);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 105);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_zhanghaoText, ui_event_zhanghaoText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mimaText, ui_event_mimaText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_denglvButton, ui_event_denglvButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuceButton, ui_event_zhuceButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
