// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void speedanimz_Animation(lv_obj_t * TargetObject, int delay);
void speedanima_Animation(lv_obj_t * TargetObject, int delay);
void revanima_Animation(lv_obj_t * TargetObject, int delay);
void revanimz_Animation(lv_obj_t * TargetObject, int delay);
void smallhandanimz_Animation(lv_obj_t * TargetObject, int delay);
void smallhandanima_Animation(lv_obj_t * TargetObject, int delay);
void sansuo_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_bg1;
lv_obj_t * ui_daolubmp;
lv_obj_t * ui_chRoller2;
lv_obj_t * ui_zzd_off1;
lv_obj_t * ui_yzd_off1;
lv_obj_t * ui_zzd_on1;
lv_obj_t * ui_yzd_on1;
lv_obj_t * ui_yhbmp1;
lv_obj_t * ui_sxbmp1;
lv_obj_t * ui_sxbmp2;
lv_obj_t * ui_time1_hour;
lv_obj_t * ui_date1;
lv_obj_t * ui_tem1;
lv_obj_t * ui_ssd1;
lv_obj_t * ui_cmzs_off1;
lv_obj_t * ui_ecozs_off1;
lv_obj_t * ui_ecozs_on1;
lv_obj_t * ui_skdzs_off2_1;
lv_obj_t * ui_skdzs_on1;
lv_obj_t * ui_dczs_off1;
lv_obj_t * ui_yyzs_off1;
lv_obj_t * ui_yjgdzs_off1;
lv_obj_t * ui_yyzs_on1;
lv_obj_t * ui_aqqnzs_off1;
lv_obj_t * ui_chgzs_off1;
lv_obj_t * ui_qcgzs_off1;
lv_obj_t * ui_aqdzs_off1;
lv_obj_t * ui_zxdzs_off1;
lv_obj_t * ui_abszs_off1;
lv_obj_t * ui_scpzs_off1;
lv_obj_t * ui_sszs_off1;
lv_obj_t * ui_zszdzs_off1;
lv_obj_t * ui_qwdzs_off1;
lv_obj_t * ui_hwdzs_off1;
lv_obj_t * ui_tcszs_off1;
lv_obj_t * ui_gzzs_off1;
lv_obj_t * ui_wxbjsgd_off1;
lv_obj_t * ui_fdjzs_off1;
lv_obj_t * ui_fdjzs_on1;
lv_obj_t * ui_abszs_yon1;
lv_obj_t * ui_sszs_yon1;
lv_obj_t * ui_hwdzs_on1;
lv_obj_t * ui_aqqmzs_on1;
lv_obj_t * ui_hcgzs_on1;
lv_obj_t * ui_qsgzs_on1;
lv_obj_t * ui_cmzs_on1;
lv_obj_t * ui_aqdzs_on1;
lv_obj_t * ui_dczs_on1;
lv_obj_t * ui_tcszs_on1;
lv_obj_t * ui_zxdzs_on1;
lv_obj_t * ui_wxbjsgd_on1;
lv_obj_t * ui_gzzs_on1;
lv_obj_t * ui_abszs_ron1;
lv_obj_t * ui_cspzs_on1;
lv_obj_t * ui_sszs_ron1;
lv_obj_t * ui_zczdzs_on1;
lv_obj_t * ui_yjgd_jon1;
lv_obj_t * ui_yjgd_yon1;
lv_obj_t * ui_speed_num_view;
lv_obj_t * ui_rev_view;
lv_obj_t * ui_speed_view;
lv_obj_t * ui_jdtspeed;
lv_obj_t * ui_menbanspeed;
lv_obj_t * ui_rev_jdt;
lv_obj_t * ui_menbanrev;
lv_obj_t * ui_hgbmp1;
lv_obj_t * ui_hgbmp2;
lv_obj_t * ui_hgbmp3;
lv_obj_t * ui_hgbmp4;
lv_obj_t * ui_Image9;
lv_obj_t * ui_gas_hand;
lv_obj_t * ui_tem_hand;
lv_obj_t * ui_rev_hand;
lv_obj_t * ui_speed_hand;
lv_obj_t * ui_speedvalue1_2;
lv_obj_t * ui_speedvalue1_1;
lv_obj_t * ui_Poffbmp;
lv_obj_t * ui_Roffbmp;
lv_obj_t * ui_Noffbmp;
lv_obj_t * ui_Doffbmp;
lv_obj_t * ui_Ponbmp;
lv_obj_t * ui_Ronbmp;
lv_obj_t * ui_Nonbmp;
lv_obj_t * ui_Donbmp;
lv_obj_t * ui_Soffbmp;
lv_obj_t * ui_Sonbmp;
lv_obj_t * ui_jbzq;
lv_obj_t * ui_jbyq;
lv_obj_t * ui_jbzyh;
lv_obj_t * ui_jbzzh;
lv_obj_t * ui_Container1;
lv_obj_t * ui_zonlic_value_mini;
lv_obj_t * ui_xingshilic_value_mini;
lv_obj_t * ui_time1_mh;
lv_obj_t * ui_time1_min;
lv_obj_t * ui_qwdzs_on1;
lv_obj_t * ui_gaszs_off;
lv_obj_t * ui_gaszs_on;
lv_obj_t * ui_watertemzs_off;
lv_obj_t * ui_watertemzs_on;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_bg2;
lv_obj_t * ui_zzd_off2;
lv_obj_t * ui_yzd_off2;
lv_obj_t * ui_zzd_on2;
lv_obj_t * ui_yzd_on2;
lv_obj_t * ui_yhbmp2;
lv_obj_t * ui_sxbmp3;
lv_obj_t * ui_sxbmp4;
lv_obj_t * ui_time2_hour;
lv_obj_t * ui_date2;
lv_obj_t * ui_tem2;
lv_obj_t * ui_ssd2;
lv_obj_t * ui_mbx2;
lv_obj_t * ui_mbs2;
lv_obj_t * ui_speedbig21;
lv_obj_t * ui_speedbig22;
lv_obj_t * ui_mode21;
lv_obj_t * ui_mode22;
lv_obj_t * ui_kmh21;
lv_obj_t * ui_kmh22;
lv_obj_t * ui_greedbox1;
lv_obj_t * ui_greedbox2;
lv_obj_t * ui_greedbox3;
lv_obj_t * ui_greedbox4;
lv_obj_t * ui_redbox1;
lv_obj_t * ui_redbox2;
lv_obj_t * ui_redbox3;
lv_obj_t * ui_redbox4;
lv_obj_t * ui_catlun;
lv_obj_t * ui_cat;
lv_obj_t * ui_kpa1;
lv_obj_t * ui_kpa2;
lv_obj_t * ui_kpa3;
lv_obj_t * ui_kpa4;
lv_obj_t * ui_lttem1;
lv_obj_t * ui_lttem2;
lv_obj_t * ui_lttem3;
lv_obj_t * ui_lttem4;
lv_obj_t * ui_tyjgz1;
lv_obj_t * ui_tyjgz2;
lv_obj_t * ui_tyjgy1;
lv_obj_t * ui_tyjgy2;
lv_obj_t * ui_aqd1;
lv_obj_t * ui_aqd2;
lv_obj_t * ui_aqd3;
lv_obj_t * ui_aqd4;
lv_obj_t * ui_aqd5;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_hgbmp22;
lv_obj_t * ui_hgbmp23;
lv_obj_t * ui_hgbmp21;
lv_obj_t * ui_hgbmp24;
lv_obj_t * ui_cmzs_off2;
lv_obj_t * ui_ecozs_off2;
lv_obj_t * ui_ecozs_on2;
lv_obj_t * ui_skdzs_off2_;
lv_obj_t * ui_skdzs_on2;
lv_obj_t * ui_dczs_off2;
lv_obj_t * ui_yyzs_off2;
lv_obj_t * ui_yjgdzs_off2;
lv_obj_t * ui_yyzs_on2;
lv_obj_t * ui_aqqnzs_off2;
lv_obj_t * ui_chgzs_off2;
lv_obj_t * ui_qcgzs_off2;
lv_obj_t * ui_aqdzs_off2;
lv_obj_t * ui_zxdzs_off2;
lv_obj_t * ui_abszs_off2;
lv_obj_t * ui_scpzs_off2;
lv_obj_t * ui_sszs_off2;
lv_obj_t * ui_zszdzs_off2;
lv_obj_t * ui_qwdzs_off2;
lv_obj_t * ui_hwdzs_off2;
lv_obj_t * ui_tcszs_off2;
lv_obj_t * ui_gzzs_off2;
lv_obj_t * ui_wxbjsgd_off2;
lv_obj_t * ui_fdjzs_off2;
lv_obj_t * ui_fdjzs_on2;
lv_obj_t * ui_abszs_yon2;
lv_obj_t * ui_sszs_yon2;
lv_obj_t * ui_hwdzs_on2;
lv_obj_t * ui_aqqmzs_on2;
lv_obj_t * ui_hcgzs_on2;
lv_obj_t * ui_qsgzs_on2;
lv_obj_t * ui_cmzs_on2;
lv_obj_t * ui_aqdzs_on2;
lv_obj_t * ui_dczs_on2;
lv_obj_t * ui_tcszs_on2;
lv_obj_t * ui_zxdzs_on2;
lv_obj_t * ui_wxbjsgd_on2;
lv_obj_t * ui_gzzs_on2;
lv_obj_t * ui_abszs_ron2;
lv_obj_t * ui_cspzs_on2;
lv_obj_t * ui_sszs_ron2;
lv_obj_t * ui_zczdzs_on2;
lv_obj_t * ui_yjgd_jon2;
lv_obj_t * ui_yjgd_yon2;
lv_obj_t * ui_time2_mh;
lv_obj_t * ui_time2_min;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_bg3;
lv_obj_t * ui_zzd_off3;
lv_obj_t * ui_yzd_off3;
lv_obj_t * ui_zzd_on3;
lv_obj_t * ui_yzd_on3;
lv_obj_t * ui_yhbmp3;
lv_obj_t * ui_sxbmp5;
lv_obj_t * ui_sxbmp6;
lv_obj_t * ui_time3_hour;
lv_obj_t * ui_date3;
lv_obj_t * ui_tem3;
lv_obj_t * ui_ssd3;
lv_obj_t * ui_mbx3;
lv_obj_t * ui_mb3;
lv_obj_t * ui_speedbig3;
lv_obj_t * ui_speedbig4;
lv_obj_t * ui_mode3;
lv_obj_t * ui_mode4;
lv_obj_t * ui_kmh3;
lv_obj_t * ui_kmh4;
lv_obj_t * ui_Roller3;
lv_obj_t * ui_hgbmp5;
lv_obj_t * ui_hgbmp6;
lv_obj_t * ui_hgbmp7;
lv_obj_t * ui_hgbmp8;
lv_obj_t * ui_cmzs_off3;
lv_obj_t * ui_ecozs_off3;
lv_obj_t * ui_ecozs_on3;
lv_obj_t * ui_skdzs_off2_2;
lv_obj_t * ui_skdzs_on3;
lv_obj_t * ui_dczs_off3;
lv_obj_t * ui_yyzs_off3;
lv_obj_t * ui_yjgdzs_off3;
lv_obj_t * ui_yyzs_on3;
lv_obj_t * ui_aqqnzs_off3;
lv_obj_t * ui_chgzs_off3;
lv_obj_t * ui_qcgzs_off3;
lv_obj_t * ui_aqdzs_off3;
lv_obj_t * ui_zxdzs_off3;
lv_obj_t * ui_abszs_off3;
lv_obj_t * ui_scpzs_off3;
lv_obj_t * ui_sszs_off3;
lv_obj_t * ui_zszdzs_off3;
lv_obj_t * ui_qwdzs_off3;
lv_obj_t * ui_hwdzs_off3;
lv_obj_t * ui_tcszs_off3;
lv_obj_t * ui_gzzs_off3;
lv_obj_t * ui_wxbjsgd_off3;
lv_obj_t * ui_fdjzs_off3;
lv_obj_t * ui_fdjzs_on3;
lv_obj_t * ui_abszs_yon3;
lv_obj_t * ui_sszs_yon3;
lv_obj_t * ui_hwdzs_on3;
lv_obj_t * ui_aqqmzs_on3;
lv_obj_t * ui_hcgzs_on3;
lv_obj_t * ui_qsgzs_on3;
lv_obj_t * ui_cmzs_on3;
lv_obj_t * ui_aqdzs_on3;
lv_obj_t * ui_dczs_on3;
lv_obj_t * ui_tcszs_on3;
lv_obj_t * ui_zxdzs_on3;
lv_obj_t * ui_wxbjsgd_on3;
lv_obj_t * ui_gzzs_on3;
lv_obj_t * ui_abszs_ron3;
lv_obj_t * ui_cspzs_on3;
lv_obj_t * ui_sszs_ron3;
lv_obj_t * ui_zczdzs_on3;
lv_obj_t * ui_yjgd_jon3;
lv_obj_t * ui_yjgd_yon3;
lv_obj_t * ui_leijilicbmp;
lv_obj_t * ui_leijisjbmp;
lv_obj_t * ui_zonlicbmp;
lv_obj_t * ui_leijihaoyoubmp;
lv_obj_t * ui_KMbmp1;
lv_obj_t * ui_KMbmp2;
lv_obj_t * ui_Hbmp1;
lv_obj_t * ui_LKMbmp1;
lv_obj_t * ui_titlebgbmp;
lv_obj_t * ui_title;
lv_obj_t * ui_leijilicconer;
lv_obj_t * ui_leijilic_value;
lv_obj_t * ui_leijisjconer;
lv_obj_t * ui_leijisjh_value;
lv_obj_t * ui_sjmh;
lv_obj_t * ui_leijisjm_value;
lv_obj_t * ui_liejiyouhaoconner;
lv_obj_t * ui_haoyouL_value;
lv_obj_t * ui_haoyoud;
lv_obj_t * ui_haoyoudL_value;
lv_obj_t * ui_zonlicconer;
lv_obj_t * ui_zonlic_value;
lv_obj_t * ui_time3_mh;
lv_obj_t * ui_time3_min;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_bg4;
lv_obj_t * ui_zzd_off4;
lv_obj_t * ui_yzd_off4;
lv_obj_t * ui_zzd_on4;
lv_obj_t * ui_yzd_on4;
lv_obj_t * ui_yhbmp4;
lv_obj_t * ui_sxbmp7;
lv_obj_t * ui_sxbmp8;
lv_obj_t * ui_time4_hour;
lv_obj_t * ui_date4;
lv_obj_t * ui_tem4;
lv_obj_t * ui_ssd4;
lv_obj_t * ui_mbx4;
lv_obj_t * ui_mbs4;
lv_obj_t * ui_speedbig5;
lv_obj_t * ui_speedbig6;
lv_obj_t * ui_mode5;
lv_obj_t * ui_mode6;
lv_obj_t * ui_kmh5;
lv_obj_t * ui_kmh6;
lv_obj_t * ui_Roller4;
lv_obj_t * ui_hgbmp9;
lv_obj_t * ui_hgbmp10;
lv_obj_t * ui_hgbmp11;
lv_obj_t * ui_hgbmp12;
lv_obj_t * ui_cmzs_off4;
lv_obj_t * ui_ecozs_off4;
lv_obj_t * ui_ecozs_on4;
lv_obj_t * ui_skdzs_off2_3;
lv_obj_t * ui_skdzs_on4;
lv_obj_t * ui_dczs_off4;
lv_obj_t * ui_yyzs_off4;
lv_obj_t * ui_yjgdzs_off4;
lv_obj_t * ui_yyzs_on4;
lv_obj_t * ui_aqqnzs_off4;
lv_obj_t * ui_chgzs_off4;
lv_obj_t * ui_qcgzs_off4;
lv_obj_t * ui_aqdzs_off4;
lv_obj_t * ui_zxdzs_off4;
lv_obj_t * ui_abszs_off4;
lv_obj_t * ui_scpzs_off4;
lv_obj_t * ui_sszs_off4;
lv_obj_t * ui_zszdzs_off4;
lv_obj_t * ui_qwdzs_off4;
lv_obj_t * ui_hwdzs_off4;
lv_obj_t * ui_tcszs_off4;
lv_obj_t * ui_gzzs_off4;
lv_obj_t * ui_wxbjsgd_off4;
lv_obj_t * ui_fdjzs_off4;
lv_obj_t * ui_fdjzs_on4;
lv_obj_t * ui_abszs_yon4;
lv_obj_t * ui_sszs_yon4;
lv_obj_t * ui_hwdzs_on4;
lv_obj_t * ui_aqqmzs_on4;
lv_obj_t * ui_hcgzs_on4;
lv_obj_t * ui_qsgzs_on4;
lv_obj_t * ui_cmzs_on4;
lv_obj_t * ui_aqdzs_on4;
lv_obj_t * ui_dczs_on4;
lv_obj_t * ui_tcszs_on4;
lv_obj_t * ui_zxdzs_on4;
lv_obj_t * ui_wxbjsgd_on4;
lv_obj_t * ui_gzzs_on4;
lv_obj_t * ui_abszs_ron4;
lv_obj_t * ui_cspzs_on4;
lv_obj_t * ui_sszs_ron4;
lv_obj_t * ui_zczdzs_on4;
lv_obj_t * ui_yjgd_jon4;
lv_obj_t * ui_yjgd_yon4;
lv_obj_t * ui_xingshilicbmp;
lv_obj_t * ui_xingshisjbmp;
lv_obj_t * ui_xingshiyouhao;
lv_obj_t * ui_Image40;
lv_obj_t * ui_Image41;
lv_obj_t * ui_Image42;
lv_obj_t * ui_Image43;
lv_obj_t * ui_Label7;
lv_obj_t * ui_xingshilicconer;
lv_obj_t * ui_xingshilic_value;
lv_obj_t * ui_xingshisjconer;
lv_obj_t * ui_xingshisjh_value;
lv_obj_t * ui_xingshisjmh;
lv_obj_t * ui_xingshisjm_value;
lv_obj_t * ui_xingshiyouhaoconer;
lv_obj_t * ui_xingshiyouhaoL_value;
lv_obj_t * ui_xinshiyouhaod;
lv_obj_t * ui_xingshiyouhaodL_value;
lv_obj_t * ui_time4_mh;
lv_obj_t * ui_time4_min;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_denglvjiemiantupian;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_denglvbiaoti;
lv_obj_t * ui_fangxiangpan;
lv_obj_t * ui_yonghuming;
void ui_event_zhanghaoText(lv_event_t * e);
lv_obj_t * ui_zhanghaoText;
lv_obj_t * ui_carkey;
lv_obj_t * ui_mima;
void ui_event_mimaText(lv_event_t * e);
lv_obj_t * ui_mimaText;
void ui_event_denglvButton(lv_event_t * e);
lv_obj_t * ui_denglvButton;
lv_obj_t * ui_denglv;
void ui_event_zhuceButton(lv_event_t * e);
lv_obj_t * ui_zhuceButton;
lv_obj_t * ui_zhuce;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1405107096[40] = {&ui_img_170937940, &ui_img_2140545812, &ui_img_2140544787, &ui_img_2140546837, &ui_img_2027840764, &ui_img_170932567, &ui_img_170934617, &ui_img_457315224, &ui_img_946112608, &ui_img_103667151, &ui_img_457314201, &ui_img_525673059, &ui_img_946109535, &ui_img_1913481532, &ui_img_1185399403, &ui_img_2027838714, &ui_img_1539046453, &ui_img_946110558, &ui_img_1539045430, &ui_img_457316251, &ui_img_1961051338, &ui_img_1539048503, &ui_img_103672274, &ui_img_457319324, &ui_img_946108508, &ui_img_1913482559, &ui_img_2027837687, &ui_img_1539047480, &ui_img_103671251, &ui_img_624410878, &ui_img_457318301, &ui_img_525677159, &ui_img_1913469232, &ui_img_1185387103, &ui_img_2027851014, &ui_img_103657924, &ui_img_1961040061, &ui_img_1913468209, &ui_img_457303951, &ui_img_525662809};
const lv_img_dsc_t * ui_imgset_1771576154[2] = {&ui_img_999003654, &ui_img_999005704};
const lv_img_dsc_t * ui_imgset_1771849361[4] = {&ui_img_1870684104, &ui_img_1870676681, &ui_img_1870682054, &ui_img_1995059043};
const lv_img_dsc_t * ui_imgset_1967689367[1] = {&ui_img_1342356983};
const lv_img_dsc_t * ui_imgset_250055599[7] = {&ui_img_815005746, &ui_img_896081354, &ui_img_896082379, &ui_img_896079304, &ui_img_896085702, &ui_img_41619278, &ui_img_41620303};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void speedanimz_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 10);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void speedanima_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, -10);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void revanima_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 34);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void revanimz_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 68);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 2);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void smallhandanimz_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 5000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 800);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void smallhandanima_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, -800);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void sansuo_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 500);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_zhanghaoText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_zhanghaoText);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_mimaText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_mimaText);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_denglvButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        denglvhanshu01(e);
    }
}
void ui_event_zhuceButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        zhucehanshu01(e);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
