// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void speedanimz_Animation(lv_obj_t * TargetObject, int delay);
void speedanima_Animation(lv_obj_t * TargetObject, int delay);
void revanima_Animation(lv_obj_t * TargetObject, int delay);
void revanimz_Animation(lv_obj_t * TargetObject, int delay);
void smallhandanimz_Animation(lv_obj_t * TargetObject, int delay);
void smallhandanima_Animation(lv_obj_t * TargetObject, int delay);
void sansuo_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_bg1;
extern lv_obj_t * ui_daolubmp;
extern lv_obj_t * ui_chRoller2;
extern lv_obj_t * ui_zzd_off1;
extern lv_obj_t * ui_yzd_off1;
extern lv_obj_t * ui_zzd_on1;
extern lv_obj_t * ui_yzd_on1;
extern lv_obj_t * ui_yhbmp1;
extern lv_obj_t * ui_sxbmp1;
extern lv_obj_t * ui_sxbmp2;
extern lv_obj_t * ui_time1_hour;
extern lv_obj_t * ui_date1;
extern lv_obj_t * ui_tem1;
extern lv_obj_t * ui_ssd1;
extern lv_obj_t * ui_cmzs_off1;
extern lv_obj_t * ui_ecozs_off1;
extern lv_obj_t * ui_ecozs_on1;
extern lv_obj_t * ui_skdzs_off2_1;
extern lv_obj_t * ui_skdzs_on1;
extern lv_obj_t * ui_dczs_off1;
extern lv_obj_t * ui_yyzs_off1;
extern lv_obj_t * ui_yjgdzs_off1;
extern lv_obj_t * ui_yyzs_on1;
extern lv_obj_t * ui_aqqnzs_off1;
extern lv_obj_t * ui_chgzs_off1;
extern lv_obj_t * ui_qcgzs_off1;
extern lv_obj_t * ui_aqdzs_off1;
extern lv_obj_t * ui_zxdzs_off1;
extern lv_obj_t * ui_abszs_off1;
extern lv_obj_t * ui_scpzs_off1;
extern lv_obj_t * ui_sszs_off1;
extern lv_obj_t * ui_zszdzs_off1;
extern lv_obj_t * ui_qwdzs_off1;
extern lv_obj_t * ui_hwdzs_off1;
extern lv_obj_t * ui_tcszs_off1;
extern lv_obj_t * ui_gzzs_off1;
extern lv_obj_t * ui_wxbjsgd_off1;
extern lv_obj_t * ui_fdjzs_off1;
extern lv_obj_t * ui_fdjzs_on1;
extern lv_obj_t * ui_abszs_yon1;
extern lv_obj_t * ui_sszs_yon1;
extern lv_obj_t * ui_hwdzs_on1;
extern lv_obj_t * ui_aqqmzs_on1;
extern lv_obj_t * ui_hcgzs_on1;
extern lv_obj_t * ui_qsgzs_on1;
extern lv_obj_t * ui_cmzs_on1;
extern lv_obj_t * ui_aqdzs_on1;
extern lv_obj_t * ui_dczs_on1;
extern lv_obj_t * ui_tcszs_on1;
extern lv_obj_t * ui_zxdzs_on1;
extern lv_obj_t * ui_wxbjsgd_on1;
extern lv_obj_t * ui_gzzs_on1;
extern lv_obj_t * ui_abszs_ron1;
extern lv_obj_t * ui_cspzs_on1;
extern lv_obj_t * ui_sszs_ron1;
extern lv_obj_t * ui_zczdzs_on1;
extern lv_obj_t * ui_yjgd_jon1;
extern lv_obj_t * ui_yjgd_yon1;
extern lv_obj_t * ui_speed_num_view;
extern lv_obj_t * ui_rev_view;
extern lv_obj_t * ui_speed_view;
extern lv_obj_t * ui_jdtspeed;
extern lv_obj_t * ui_menbanspeed;
extern lv_obj_t * ui_rev_jdt;
extern lv_obj_t * ui_menbanrev;
extern lv_obj_t * ui_hgbmp1;
extern lv_obj_t * ui_hgbmp2;
extern lv_obj_t * ui_hgbmp3;
extern lv_obj_t * ui_hgbmp4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_gas_hand;
extern lv_obj_t * ui_tem_hand;
extern lv_obj_t * ui_rev_hand;
extern lv_obj_t * ui_speed_hand;
extern lv_obj_t * ui_speedvalue1_2;
extern lv_obj_t * ui_speedvalue1_1;
extern lv_obj_t * ui_Poffbmp;
extern lv_obj_t * ui_Roffbmp;
extern lv_obj_t * ui_Noffbmp;
extern lv_obj_t * ui_Doffbmp;
extern lv_obj_t * ui_Ponbmp;
extern lv_obj_t * ui_Ronbmp;
extern lv_obj_t * ui_Nonbmp;
extern lv_obj_t * ui_Donbmp;
extern lv_obj_t * ui_Soffbmp;
extern lv_obj_t * ui_Sonbmp;
extern lv_obj_t * ui_jbzq;
extern lv_obj_t * ui_jbyq;
extern lv_obj_t * ui_jbzyh;
extern lv_obj_t * ui_jbzzh;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_zonlic_value_mini;
extern lv_obj_t * ui_xingshilic_value_mini;
extern lv_obj_t * ui_time1_mh;
extern lv_obj_t * ui_time1_min;
extern lv_obj_t * ui_qwdzs_on1;
extern lv_obj_t * ui_gaszs_off;
extern lv_obj_t * ui_gaszs_on;
extern lv_obj_t * ui_watertemzs_off;
extern lv_obj_t * ui_watertemzs_on;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_bg2;
extern lv_obj_t * ui_zzd_off2;
extern lv_obj_t * ui_yzd_off2;
extern lv_obj_t * ui_zzd_on2;
extern lv_obj_t * ui_yzd_on2;
extern lv_obj_t * ui_yhbmp2;
extern lv_obj_t * ui_sxbmp3;
extern lv_obj_t * ui_sxbmp4;
extern lv_obj_t * ui_time2_hour;
extern lv_obj_t * ui_date2;
extern lv_obj_t * ui_tem2;
extern lv_obj_t * ui_ssd2;
extern lv_obj_t * ui_mbx2;
extern lv_obj_t * ui_mbs2;
extern lv_obj_t * ui_speedbig21;
extern lv_obj_t * ui_speedbig22;
extern lv_obj_t * ui_mode21;
extern lv_obj_t * ui_mode22;
extern lv_obj_t * ui_kmh21;
extern lv_obj_t * ui_kmh22;
extern lv_obj_t * ui_greedbox1;
extern lv_obj_t * ui_greedbox2;
extern lv_obj_t * ui_greedbox3;
extern lv_obj_t * ui_greedbox4;
extern lv_obj_t * ui_redbox1;
extern lv_obj_t * ui_redbox2;
extern lv_obj_t * ui_redbox3;
extern lv_obj_t * ui_redbox4;
extern lv_obj_t * ui_catlun;
extern lv_obj_t * ui_cat;
extern lv_obj_t * ui_kpa1;
extern lv_obj_t * ui_kpa2;
extern lv_obj_t * ui_kpa3;
extern lv_obj_t * ui_kpa4;
extern lv_obj_t * ui_lttem1;
extern lv_obj_t * ui_lttem2;
extern lv_obj_t * ui_lttem3;
extern lv_obj_t * ui_lttem4;
extern lv_obj_t * ui_tyjgz1;
extern lv_obj_t * ui_tyjgz2;
extern lv_obj_t * ui_tyjgy1;
extern lv_obj_t * ui_tyjgy2;
extern lv_obj_t * ui_aqd1;
extern lv_obj_t * ui_aqd2;
extern lv_obj_t * ui_aqd3;
extern lv_obj_t * ui_aqd4;
extern lv_obj_t * ui_aqd5;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_hgbmp22;
extern lv_obj_t * ui_hgbmp23;
extern lv_obj_t * ui_hgbmp21;
extern lv_obj_t * ui_hgbmp24;
extern lv_obj_t * ui_cmzs_off2;
extern lv_obj_t * ui_ecozs_off2;
extern lv_obj_t * ui_ecozs_on2;
extern lv_obj_t * ui_skdzs_off2_;
extern lv_obj_t * ui_skdzs_on2;
extern lv_obj_t * ui_dczs_off2;
extern lv_obj_t * ui_yyzs_off2;
extern lv_obj_t * ui_yjgdzs_off2;
extern lv_obj_t * ui_yyzs_on2;
extern lv_obj_t * ui_aqqnzs_off2;
extern lv_obj_t * ui_chgzs_off2;
extern lv_obj_t * ui_qcgzs_off2;
extern lv_obj_t * ui_aqdzs_off2;
extern lv_obj_t * ui_zxdzs_off2;
extern lv_obj_t * ui_abszs_off2;
extern lv_obj_t * ui_scpzs_off2;
extern lv_obj_t * ui_sszs_off2;
extern lv_obj_t * ui_zszdzs_off2;
extern lv_obj_t * ui_qwdzs_off2;
extern lv_obj_t * ui_hwdzs_off2;
extern lv_obj_t * ui_tcszs_off2;
extern lv_obj_t * ui_gzzs_off2;
extern lv_obj_t * ui_wxbjsgd_off2;
extern lv_obj_t * ui_fdjzs_off2;
extern lv_obj_t * ui_fdjzs_on2;
extern lv_obj_t * ui_abszs_yon2;
extern lv_obj_t * ui_sszs_yon2;
extern lv_obj_t * ui_hwdzs_on2;
extern lv_obj_t * ui_aqqmzs_on2;
extern lv_obj_t * ui_hcgzs_on2;
extern lv_obj_t * ui_qsgzs_on2;
extern lv_obj_t * ui_cmzs_on2;
extern lv_obj_t * ui_aqdzs_on2;
extern lv_obj_t * ui_dczs_on2;
extern lv_obj_t * ui_tcszs_on2;
extern lv_obj_t * ui_zxdzs_on2;
extern lv_obj_t * ui_wxbjsgd_on2;
extern lv_obj_t * ui_gzzs_on2;
extern lv_obj_t * ui_abszs_ron2;
extern lv_obj_t * ui_cspzs_on2;
extern lv_obj_t * ui_sszs_ron2;
extern lv_obj_t * ui_zczdzs_on2;
extern lv_obj_t * ui_yjgd_jon2;
extern lv_obj_t * ui_yjgd_yon2;
extern lv_obj_t * ui_time2_mh;
extern lv_obj_t * ui_time2_min;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_bg3;
extern lv_obj_t * ui_zzd_off3;
extern lv_obj_t * ui_yzd_off3;
extern lv_obj_t * ui_zzd_on3;
extern lv_obj_t * ui_yzd_on3;
extern lv_obj_t * ui_yhbmp3;
extern lv_obj_t * ui_sxbmp5;
extern lv_obj_t * ui_sxbmp6;
extern lv_obj_t * ui_time3_hour;
extern lv_obj_t * ui_date3;
extern lv_obj_t * ui_tem3;
extern lv_obj_t * ui_ssd3;
extern lv_obj_t * ui_mbx3;
extern lv_obj_t * ui_mb3;
extern lv_obj_t * ui_speedbig3;
extern lv_obj_t * ui_speedbig4;
extern lv_obj_t * ui_mode3;
extern lv_obj_t * ui_mode4;
extern lv_obj_t * ui_kmh3;
extern lv_obj_t * ui_kmh4;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_hgbmp5;
extern lv_obj_t * ui_hgbmp6;
extern lv_obj_t * ui_hgbmp7;
extern lv_obj_t * ui_hgbmp8;
extern lv_obj_t * ui_cmzs_off3;
extern lv_obj_t * ui_ecozs_off3;
extern lv_obj_t * ui_ecozs_on3;
extern lv_obj_t * ui_skdzs_off2_2;
extern lv_obj_t * ui_skdzs_on3;
extern lv_obj_t * ui_dczs_off3;
extern lv_obj_t * ui_yyzs_off3;
extern lv_obj_t * ui_yjgdzs_off3;
extern lv_obj_t * ui_yyzs_on3;
extern lv_obj_t * ui_aqqnzs_off3;
extern lv_obj_t * ui_chgzs_off3;
extern lv_obj_t * ui_qcgzs_off3;
extern lv_obj_t * ui_aqdzs_off3;
extern lv_obj_t * ui_zxdzs_off3;
extern lv_obj_t * ui_abszs_off3;
extern lv_obj_t * ui_scpzs_off3;
extern lv_obj_t * ui_sszs_off3;
extern lv_obj_t * ui_zszdzs_off3;
extern lv_obj_t * ui_qwdzs_off3;
extern lv_obj_t * ui_hwdzs_off3;
extern lv_obj_t * ui_tcszs_off3;
extern lv_obj_t * ui_gzzs_off3;
extern lv_obj_t * ui_wxbjsgd_off3;
extern lv_obj_t * ui_fdjzs_off3;
extern lv_obj_t * ui_fdjzs_on3;
extern lv_obj_t * ui_abszs_yon3;
extern lv_obj_t * ui_sszs_yon3;
extern lv_obj_t * ui_hwdzs_on3;
extern lv_obj_t * ui_aqqmzs_on3;
extern lv_obj_t * ui_hcgzs_on3;
extern lv_obj_t * ui_qsgzs_on3;
extern lv_obj_t * ui_cmzs_on3;
extern lv_obj_t * ui_aqdzs_on3;
extern lv_obj_t * ui_dczs_on3;
extern lv_obj_t * ui_tcszs_on3;
extern lv_obj_t * ui_zxdzs_on3;
extern lv_obj_t * ui_wxbjsgd_on3;
extern lv_obj_t * ui_gzzs_on3;
extern lv_obj_t * ui_abszs_ron3;
extern lv_obj_t * ui_cspzs_on3;
extern lv_obj_t * ui_sszs_ron3;
extern lv_obj_t * ui_zczdzs_on3;
extern lv_obj_t * ui_yjgd_jon3;
extern lv_obj_t * ui_yjgd_yon3;
extern lv_obj_t * ui_leijilicbmp;
extern lv_obj_t * ui_leijisjbmp;
extern lv_obj_t * ui_zonlicbmp;
extern lv_obj_t * ui_leijihaoyoubmp;
extern lv_obj_t * ui_KMbmp1;
extern lv_obj_t * ui_KMbmp2;
extern lv_obj_t * ui_Hbmp1;
extern lv_obj_t * ui_LKMbmp1;
extern lv_obj_t * ui_titlebgbmp;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_leijilicconer;
extern lv_obj_t * ui_leijilic_value;
extern lv_obj_t * ui_leijisjconer;
extern lv_obj_t * ui_leijisjh_value;
extern lv_obj_t * ui_sjmh;
extern lv_obj_t * ui_leijisjm_value;
extern lv_obj_t * ui_liejiyouhaoconner;
extern lv_obj_t * ui_haoyouL_value;
extern lv_obj_t * ui_haoyoud;
extern lv_obj_t * ui_haoyoudL_value;
extern lv_obj_t * ui_zonlicconer;
extern lv_obj_t * ui_zonlic_value;
extern lv_obj_t * ui_time3_mh;
extern lv_obj_t * ui_time3_min;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_bg4;
extern lv_obj_t * ui_zzd_off4;
extern lv_obj_t * ui_yzd_off4;
extern lv_obj_t * ui_zzd_on4;
extern lv_obj_t * ui_yzd_on4;
extern lv_obj_t * ui_yhbmp4;
extern lv_obj_t * ui_sxbmp7;
extern lv_obj_t * ui_sxbmp8;
extern lv_obj_t * ui_time4_hour;
extern lv_obj_t * ui_date4;
extern lv_obj_t * ui_tem4;
extern lv_obj_t * ui_ssd4;
extern lv_obj_t * ui_mbx4;
extern lv_obj_t * ui_mbs4;
extern lv_obj_t * ui_speedbig5;
extern lv_obj_t * ui_speedbig6;
extern lv_obj_t * ui_mode5;
extern lv_obj_t * ui_mode6;
extern lv_obj_t * ui_kmh5;
extern lv_obj_t * ui_kmh6;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_hgbmp9;
extern lv_obj_t * ui_hgbmp10;
extern lv_obj_t * ui_hgbmp11;
extern lv_obj_t * ui_hgbmp12;
extern lv_obj_t * ui_cmzs_off4;
extern lv_obj_t * ui_ecozs_off4;
extern lv_obj_t * ui_ecozs_on4;
extern lv_obj_t * ui_skdzs_off2_3;
extern lv_obj_t * ui_skdzs_on4;
extern lv_obj_t * ui_dczs_off4;
extern lv_obj_t * ui_yyzs_off4;
extern lv_obj_t * ui_yjgdzs_off4;
extern lv_obj_t * ui_yyzs_on4;
extern lv_obj_t * ui_aqqnzs_off4;
extern lv_obj_t * ui_chgzs_off4;
extern lv_obj_t * ui_qcgzs_off4;
extern lv_obj_t * ui_aqdzs_off4;
extern lv_obj_t * ui_zxdzs_off4;
extern lv_obj_t * ui_abszs_off4;
extern lv_obj_t * ui_scpzs_off4;
extern lv_obj_t * ui_sszs_off4;
extern lv_obj_t * ui_zszdzs_off4;
extern lv_obj_t * ui_qwdzs_off4;
extern lv_obj_t * ui_hwdzs_off4;
extern lv_obj_t * ui_tcszs_off4;
extern lv_obj_t * ui_gzzs_off4;
extern lv_obj_t * ui_wxbjsgd_off4;
extern lv_obj_t * ui_fdjzs_off4;
extern lv_obj_t * ui_fdjzs_on4;
extern lv_obj_t * ui_abszs_yon4;
extern lv_obj_t * ui_sszs_yon4;
extern lv_obj_t * ui_hwdzs_on4;
extern lv_obj_t * ui_aqqmzs_on4;
extern lv_obj_t * ui_hcgzs_on4;
extern lv_obj_t * ui_qsgzs_on4;
extern lv_obj_t * ui_cmzs_on4;
extern lv_obj_t * ui_aqdzs_on4;
extern lv_obj_t * ui_dczs_on4;
extern lv_obj_t * ui_tcszs_on4;
extern lv_obj_t * ui_zxdzs_on4;
extern lv_obj_t * ui_wxbjsgd_on4;
extern lv_obj_t * ui_gzzs_on4;
extern lv_obj_t * ui_abszs_ron4;
extern lv_obj_t * ui_cspzs_on4;
extern lv_obj_t * ui_sszs_ron4;
extern lv_obj_t * ui_zczdzs_on4;
extern lv_obj_t * ui_yjgd_jon4;
extern lv_obj_t * ui_yjgd_yon4;
extern lv_obj_t * ui_xingshilicbmp;
extern lv_obj_t * ui_xingshisjbmp;
extern lv_obj_t * ui_xingshiyouhao;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Image41;
extern lv_obj_t * ui_Image42;
extern lv_obj_t * ui_Image43;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_xingshilicconer;
extern lv_obj_t * ui_xingshilic_value;
extern lv_obj_t * ui_xingshisjconer;
extern lv_obj_t * ui_xingshisjh_value;
extern lv_obj_t * ui_xingshisjmh;
extern lv_obj_t * ui_xingshisjm_value;
extern lv_obj_t * ui_xingshiyouhaoconer;
extern lv_obj_t * ui_xingshiyouhaoL_value;
extern lv_obj_t * ui_xinshiyouhaod;
extern lv_obj_t * ui_xingshiyouhaodL_value;
extern lv_obj_t * ui_time4_mh;
extern lv_obj_t * ui_time4_min;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_denglvjiemiantupian;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_denglvbiaoti;
extern lv_obj_t * ui_fangxiangpan;
extern lv_obj_t * ui_yonghuming;
void ui_event_zhanghaoText(lv_event_t * e);
extern lv_obj_t * ui_zhanghaoText;
extern lv_obj_t * ui_carkey;
extern lv_obj_t * ui_mima;
void ui_event_mimaText(lv_event_t * e);
extern lv_obj_t * ui_mimaText;
void ui_event_denglvButton(lv_event_t * e);
extern lv_obj_t * ui_denglvButton;
extern lv_obj_t * ui_denglv;
void ui_event_zhuceButton(lv_event_t * e);
extern lv_obj_t * ui_zhuceButton;
extern lv_obj_t * ui_zhuce;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1342356983);    // assets/矩形 3_1.png
LV_IMG_DECLARE(ui_img_851353715);    // assets/分组 56 (2).png
LV_IMG_DECLARE(ui_img_896079304);    // assets/路径 194.png
LV_IMG_DECLARE(ui_img_1642931740);    // assets/路径 194（1）.png
LV_IMG_DECLARE(ui_img_896081354);    // assets/路径 192.png
LV_IMG_DECLARE(ui_img_896082379);    // assets/路径 193.png
LV_IMG_DECLARE(ui_img_999003654);    // assets/圆形 1.png
LV_IMG_DECLARE(ui_img_1995059043);    // assets/矩形 18.png
LV_IMG_DECLARE(ui_img_525677159);    // assets/分组 79.png
LV_IMG_DECLARE(ui_img_1717054016);    // assets/ECO（1）.png
LV_IMG_DECLARE(ui_img_eco_png);    // assets/ECO.png
LV_IMG_DECLARE(ui_img_1837894125);    // assets/位置灯（1）.png
LV_IMG_DECLARE(ui_img_2027284395);    // assets/位置灯.png
LV_IMG_DECLARE(ui_img_2140545812);    // assets/分组 100.png
LV_IMG_DECLARE(ui_img_2140544787);    // assets/分组 101.png
LV_IMG_DECLARE(ui_img_2140546837);    // assets/分组 103.png
LV_IMG_DECLARE(ui_img_946112608);    // assets/分组 30.png
LV_IMG_DECLARE(ui_img_103671251);    // assets/分组 75.png
LV_IMG_DECLARE(ui_img_624410878);    // assets/分组 76.png
LV_IMG_DECLARE(ui_img_457318301);    // assets/分组 77.png
LV_IMG_DECLARE(ui_img_1572821649);    // assets/分组 79（1）.png
LV_IMG_DECLARE(ui_img_1913469232);    // assets/分组 81.png
LV_IMG_DECLARE(ui_img_1185387103);    // assets/分组 82.png
LV_IMG_DECLARE(ui_img_2027851014);    // assets/分组 83.png
LV_IMG_DECLARE(ui_img_1092003334);    // assets/分组 83（1）.png
LV_IMG_DECLARE(ui_img_1976030069);    // assets/分组 84（1）.png
LV_IMG_DECLARE(ui_img_103657924);    // assets/分组 85.png
LV_IMG_DECLARE(ui_img_1961040061);    // assets/分组 88.png
LV_IMG_DECLARE(ui_img_1913468209);    // assets/分组 91.png
LV_IMG_DECLARE(ui_img_457303951);    // assets/分组 97.png
LV_IMG_DECLARE(ui_img_525662809);    // assets/分组 99.png
LV_IMG_DECLARE(ui_img_1926959430);    // assets/发动机异常（1）.png
LV_IMG_DECLARE(ui_img_986460666);    // assets/发动机异常.png
LV_IMG_DECLARE(ui_img_1539047480);    // assets/分组 74.png
LV_IMG_DECLARE(ui_img_2027837687);    // assets/分组 73.png
LV_IMG_DECLARE(ui_img_1913482559);    // assets/分组 71.png
LV_IMG_DECLARE(ui_img_457319324);    // assets/分组 67.png
LV_IMG_DECLARE(ui_img_103672274);    // assets/分组 65.png
LV_IMG_DECLARE(ui_img_1539048503);    // assets/分组 64.png
LV_IMG_DECLARE(ui_img_1961051338);    // assets/分组 58.png
LV_IMG_DECLARE(ui_img_457316251);    // assets/分组 57.png
LV_IMG_DECLARE(ui_img_1539045430);    // assets/分组 54.png
LV_IMG_DECLARE(ui_img_946110558);    // assets/分组 50.png
LV_IMG_DECLARE(ui_img_1539046453);    // assets/分组 44.png
LV_IMG_DECLARE(ui_img_2027838714);    // assets/分组 43.png
LV_IMG_DECLARE(ui_img_1185399403);    // assets/分组 42.png
LV_IMG_DECLARE(ui_img_1913481532);    // assets/分组 41.png
LV_IMG_DECLARE(ui_img_946109535);    // assets/分组 40.png
LV_IMG_DECLARE(ui_img_525673059);    // assets/分组 39.png
LV_IMG_DECLARE(ui_img_457314201);    // assets/分组 37.png
LV_IMG_DECLARE(ui_img_103667151);    // assets/分组 35.png
LV_IMG_DECLARE(ui_img_170937940);    // assets/分组 1.png
LV_IMG_DECLARE(ui_img_170934617);    // assets/分组 6.png
LV_IMG_DECLARE(ui_img_170932567);    // assets/分组 4.png
LV_IMG_DECLARE(ui_img_1519863221);    // assets/分组 19 (1).png
LV_IMG_DECLARE(ui_img_981208607);    // assets/矩形 25 (1).png
LV_IMG_DECLARE(ui_img_724779459);    // assets/蒙版speed.png
LV_IMG_DECLARE(ui_img_769222035);    // assets/蒙版rev.png
LV_IMG_DECLARE(ui_img_1870676681);    // assets/矩形 3.png
LV_IMG_DECLARE(ui_img_1870682054);    // assets/矩形 4.png
LV_IMG_DECLARE(ui_img_cat_png);    // assets/cat.png
LV_IMG_DECLARE(ui_img_815005746);    // assets/路径 181.png
LV_IMG_DECLARE(ui_img_946108508);    // assets/分组 70.png
LV_IMG_DECLARE(ui_img_1892395617);    // assets/P（1）.png
LV_IMG_DECLARE(ui_img_868676823);    // assets/R（1）.png
LV_IMG_DECLARE(ui_img_1284881333);    // assets/N（1）.png
LV_IMG_DECLARE(ui_img_1785161219);    // assets/D（1）.png
LV_IMG_DECLARE(ui_img_p_png);    // assets/P.png
LV_IMG_DECLARE(ui_img_r_png);    // assets/R.png
LV_IMG_DECLARE(ui_img_n_png);    // assets/N.png
LV_IMG_DECLARE(ui_img_d_png);    // assets/D.png
LV_IMG_DECLARE(ui_img_665461724);    // assets/S（1）.png
LV_IMG_DECLARE(ui_img_s_png);    // assets/S.png
LV_IMG_DECLARE(ui_img_1548035452);    // assets/警报.png
LV_IMG_DECLARE(ui_img_2027840764);    // assets/分组 23.png
LV_IMG_DECLARE(ui_img_896085702);    // assets/路径 196.png
LV_IMG_DECLARE(ui_img_180952517);    // assets/路径 162 (1).png
LV_IMG_DECLARE(ui_img_41620303);    // assets/路径 9.png
LV_IMG_DECLARE(ui_img_41619278);    // assets/路径 8.png
LV_IMG_DECLARE(ui_img_95555192);    // assets/矩形 2（1）.png
LV_IMG_DECLARE(ui_img_1870684104);    // assets/矩形 2.png
LV_IMG_DECLARE(ui_img_rl_card_png);    // assets/RL card.png
LV_IMG_DECLARE(ui_img_fr_card_png);    // assets/FR card.png
LV_IMG_DECLARE(ui_img_tyres_png);    // assets/Tyres.png
LV_IMG_DECLARE(ui_img_car_png);    // assets/Car.png
LV_IMG_DECLARE(ui_img_95451801);    // assets/矩形 3（1）.png
LV_IMG_DECLARE(ui_img_999005704);    // assets/圆形 3.png
LV_IMG_DECLARE(ui_img_667405251);    // assets/总里程.png
LV_IMG_DECLARE(ui_img_457315224);    // assets/分组 27.png
LV_IMG_DECLARE(ui_img_km_png);    // assets/km.png
LV_IMG_DECLARE(ui_img_h_png);    // assets/h.png
LV_IMG_DECLARE(ui_img_100km_png);    // assets/100km.png
LV_IMG_DECLARE(ui_img_1482924002);    // assets/标题框.png
LV_IMG_DECLARE(ui_img_loadcar_png);    // assets/loadcar.png
LV_IMG_DECLARE(ui_img_fxp_png);    // assets/fxp.png
LV_IMG_DECLARE(ui_img_carkey_png);    // assets/carkey.png



LV_FONT_DECLARE(ui_font_big);
LV_FONT_DECLARE(ui_font_big1);
LV_FONT_DECLARE(ui_font_date_font);
LV_FONT_DECLARE(ui_font_LCDbbig);
LV_FONT_DECLARE(ui_font_LCDbig);
LV_FONT_DECLARE(ui_font_LCDmid);
LV_FONT_DECLARE(ui_font_LCDsmall);
LV_FONT_DECLARE(ui_font_liteLCD);
LV_FONT_DECLARE(ui_font_mid);
LV_FONT_DECLARE(ui_font_myfond_11);
LV_FONT_DECLARE(ui_font_myfond__1);
LV_FONT_DECLARE(ui_font_myfond__2);
LV_FONT_DECLARE(ui_font_myfond__3);
LV_FONT_DECLARE(ui_font_myfond__4);
LV_FONT_DECLARE(ui_font_myfond__5);
LV_FONT_DECLARE(ui_font_ssd);
LV_FONT_DECLARE(ui_font_denglvjiemian);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
