// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <stdio.h>
#include "ui.h"

void denglvhanshu01(lv_event_t * e)
{
    // Your code here
}

void zhucehanshu01(lv_event_t * e)
{
    // Your code here
}
